Repository metwork-framework/mfext, pull requests merged in 2018-11, with the labels that each got.

#50 feat: add pytest package and update some other ones
  layers/layer7_python2_devtools/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer7_python2_devtools/0500_extra_python_packages/requirements2.txt
  layers/layer7_python3_devtools/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer7_python3_devtools/0500_extra_python_packages/requirements3.txt
Labels: Status: Review Needed

#64 feat: upgrade eccodes to 2.9.0
  layers/layer1_scientific/0030_eccodes/Makefile.mk
  layers/layer1_scientific/0030_eccodes/sources
  layers/layer4_python2_scientific/0611_eccodes/Makefile.mk
  layers/layer4_python2_scientific/0611_eccodes/sources
Labels: Status: Review Needed

#70 feat: add mapserverapi library
  layers/layer3_mapserver/0600_mapserverapi/Makefile
  layers/layer3_mapserver/0600_mapserverapi/Makefile.mk
  layers/layer3_mapserver/0600_mapserverapi/sources
Labels: Status: Review Needed

#85 fix: mfxxx login problems in docker mode
  adm2/_metwork.spec
Labels: Status: Review Needed

#92 feat: now we can use pip inside a "plugin env"
  adm2/templates/interactive_profile
Labels: Merge Now, Status: Pending

#90 feat: patch certifi for using system certificates on centos
  layers/layer1_python2_core/0100_certifi/Makefile
  layers/layer1_python2_core/0100_certifi/Makefile.mk
  layers/layer1_python2_core/0100_certifi/certifi-system-cert-on-centos-rhel.patch
  layers/layer1_python2_core/0100_certifi/patches
  layers/layer1_python2_core/0100_certifi/sources
  layers/layer1_python3_core/0100_certifi/Makefile
  layers/layer1_python3_core/0100_certifi/Makefile.mk
  layers/layer1_python3_core/0100_certifi/certifi-system-cert-on-centos-rhel.patch
  layers/layer1_python3_core/0100_certifi/patches
  layers/layer1_python3_core/0100_certifi/sources
Labels: Merge Now, Status: Review Needed

#94 fix: add mapserverapi_python
  layers/layer4_python3_scientific/0500_extra_packages/requirements3.txt
Labels: Merge Now, Status: Review Needed

#82 [DO NOT MERGE] share caches between integration, master, ci_* and pci_* branches
  .drone.yml
Labels: Status: Review Needed

#98 build: shared cache fix
  adm2/_metwork.spec
Labels: Merge Now, Status: Pending

#100 share cache between integration, master, ci_* and pci_* branches
  .drone.yml
  adm2/_metwork.spec
Labels: Status: Revision Needed

#102 build: fix typo for mfserv build
  adm2/_metwork.spec
Labels: Status: Pending

#103 build: better build cache hash (again)
  .drone.yml
  adm/_prelayers_hash.sh
  adm2/_build_cache_hash.sh
Labels: Merge Now, Status: Pending

#101 build: faster rpm packaging
  adm/main_root.mk
  adm2/_metwork.spec
Labels: Status: Pending

#104 build: fix packaging issue introduced by latest changes
  adm2/_metwork.spec
Labels: Merge Now, Status: Review Needed

#105 build: add which as a core dependency
  adm2/_metwork.spec
Labels: Status: Review Needed

#106 build: trigger testimage builds
  .drone.yml
Labels: Merge Now, Status: Review Needed

#107 add lscpu dependency
  adm2/_metwork.spec
Labels: Merge Now, Status: Review Needed

#108 build: fix runtime dependencies for centos6
  adm2/_metwork.spec
Labels: Merge Now, Status: Review Needed

#113 fix: block mfxxx.start/stop/status/init calls from a plugin_env
  adm2/templates/mfxxx.init
  adm2/templates/mfxxx.start
  adm2/templates/mfxxx.status
  adm2/templates/mfxxx.stop
Labels: Status: Review Needed

#96 [DO NOT MERGE] feat: use normal "npm" workflow inside a "plugin_env"
  adm2/templates/bash_profile
  adm2/templates/interactive_profile
Labels: Status: Review Needed

#116 Update README.md
  .metwork-framework/README.md
Labels: Status: Review Needed

#120 build: migrate integration tests system
  .drone.yml
  adm2/_metwork.spec
  integration_tests/0001_test_python2_sqlite3/.layerapi2_dependencies
  integration_tests/0001_test_python2_sqlite3/test_python2_sqlite3.py
  integration_tests/0001_test_python2_sqlite3/test_python2_sqlite3.sh
  integration_tests/0001_test_python3_sqlite3/.layerapi2_dependencies
  integration_tests/0001_test_python3_sqlite3/test_python3_sqlite3.py
  integration_tests/0001_test_python3_sqlite3/test_python3_sqlite3.sh
  integration_tests/0002_test_python2_mapserverapi/.layerapi2_dependencies
  integration_tests/0002_test_python2_mapserverapi/test_datas/ne_110m_land.README.html
  integration_tests/0002_test_python2_mapserverapi/test_datas/ne_110m_land.VERSION.txt
  integration_tests/0002_test_python2_mapserverapi/test_datas/ne_110m_land.cpg
  integration_tests/0002_test_python2_mapserverapi/test_datas/ne_110m_land.dbf
  integration_tests/0002_test_python2_mapserverapi/test_datas/ne_110m_land.prj
  integration_tests/0002_test_python2_mapserverapi/test_datas/ne_110m_land.shp
  integration_tests/0002_test_python2_mapserverapi/test_datas/ne_110m_land.shx
  integration_tests/0002_test_python2_mapserverapi/test_datas/ne_110m_ocean.README.html
  integration_tests/0002_test_python2_mapserverapi/test_datas/ne_110m_ocean.VERSION.txt
  integration_tests/0002_test_python2_mapserverapi/test_datas/ne_110m_ocean.cpg
  integration_tests/0002_test_python2_mapserverapi/test_datas/ne_110m_ocean.dbf
  integration_tests/0002_test_python2_mapserverapi/test_datas/ne_110m_ocean.prj
  integration_tests/0002_test_python2_mapserverapi/test_datas/ne_110m_ocean.shp
  integration_tests/0002_test_python2_mapserverapi/test_datas/ne_110m_ocean.shx
  integration_tests/0002_test_python2_mapserverapi/test_datas/test.map
  integration_tests/0002_test_python2_mapserverapi/test_python2_mapserverapi.py
  integration_tests/0002_test_python2_mapserverapi/test_python2_mapserverapi.sh
  integration_tests/0002_test_python3_mapserverapi/.layerapi2_dependencies
  integration_tests/0002_test_python3_mapserverapi/test_datas
  integration_tests/0002_test_python3_mapserverapi/test_python3_mapserverapi.py
  integration_tests/0002_test_python3_mapserverapi/test_python3_mapserverapi.sh
  layers/layer9_integration_tests/.layerapi2_dependencies
  layers/layer9_integration_tests/.layerapi2_label
  layers/layer9_integration_tests/0001_test_python2_sqlite3/Makefile
  layers/layer9_integration_tests/0001_test_python2_sqlite3/Makefile.mk
  layers/layer9_integration_tests/0001_test_python3_sqlite3/Makefile
  layers/layer9_integration_tests/0001_test_python3_sqlite3/Makefile.mk
  layers/layer9_integration_tests/0002_test_python2_mapserverapi/Makefile
  layers/layer9_integration_tests/0002_test_python2_mapserverapi/Makefile.mk
  layers/layer9_integration_tests/0002_test_python3_mapserverapi/Makefile
  layers/layer9_integration_tests/0002_test_python3_mapserverapi/Makefile.mk
  layers/layer9_integration_tests/Makefile
Labels: Status: Review Needed

#121 feat: add geos, lxml, pycurl, pyproj and sqlalchemy
  layers/layer4_python3_scientific/0500_extra_packages/requirements-to-freeze.txt
  layers/layer4_python3_scientific/0500_extra_packages/requirements3.txt
Labels: Status: Review Needed

#123 feat: check that module crontab is not empy in mfxxx.status
  adm2/templates/mfxxx.status
Labels: Merge Now, Status: Review Needed

#125 Update .drone.yml
  .drone.yml
Labels: Merge Now, Status: Pending

#126 Update .drone.yml
  .drone.yml
Labels: Merge Now, Status: Review Needed

#128 feat: better default MODULE_RUNTIME_SUFFIX
  adm2/templates/profile
Labels: Merge Now, Status: Review Needed

#129 feat: Add possibility to pip install package from https url.
  layers/_pip_package_to_yaml.sh
  layers/layer1_python3_core/0000_adm/download_compile_requirements
  layers/layer1_python3_core/0000_adm/freeze_requirements
  layers/layer1_python3_core/0000_adm/install_requirements
Labels: Merge Now, Status: Review Needed

#131 Issue127
  layers/_pip_package_to_yaml.sh
Labels: Status: Review Needed

#130 feat: guess released versions with tags
  adm/guess_version.sh
Labels: Merge Now, Status: Pending

#132 Issue127
  layers/layer1_python3_core/0000_adm/freeze_requirements
Labels: Merge Now, Status: Pending
