Repository metwork-framework/mfext, pull requests merged in 2018-10, with the labels that each got.

#17 add mergify support
  .mergify.yml
Labels: Status: Review Needed, Type: To Categorize

#20 chore: better build cache
  .drone.yml
Labels: Status: Review Needed, Type: To Categorize

#21 chore: readd /buildcache volume in build step
  .drone.yml
Labels: Status: Review Needed, Type: To Categorize

#22 chore: new conditional downstream
  .drone.yml
Labels: Priority: High, Status: Accepted, Type: Enhancement

#23 chore: move boost from core layer to scientific layer
  layers/layer1_scientific/0001_boost/Makefile
  layers/layer1_scientific/0001_boost/Makefile.mk
  layers/layer1_scientific/0001_boost/sources
  layers/layer4_python2_scientific/0621_magics/Makefile.mk
  layers/layer4_python3_scientific/0621_magics/Makefile.mk
Labels: Status: Review Needed, Type: To Categorize

#24 chore: package createrepo is now in build image
  .drone.yml
Labels: Status: Review Needed, Type: To Categorize

#35 build: ignore all .md and .yml files for computing build hash
  adm2/_build_cache_hash.sh
Labels: Status: Review Needed

#38 chore: add trigger_tests to run integration tests
  .drone.yml
Labels: Status: Review Needed

#43 temp revert of #38
  .drone.yml
Labels: Status: Review Needed

#48 build: potentially faster build for ci_* branches
  .drone.yml
Labels: Status: Review Needed

#54 feat: mapserver introduction
  adm2/_metwork.spec
  layers/layer3_mapserver/.layerapi2_dependencies
  layers/layer3_mapserver/.layerapi2_label
  layers/layer3_mapserver/0450_cairo/Makefile
  layers/layer3_mapserver/0450_cairo/Makefile.mk
  layers/layer3_mapserver/0450_cairo/sources
  layers/layer3_mapserver/0500_mapserver/Makefile
  layers/layer3_mapserver/0500_mapserver/Makefile.mk
  layers/layer3_mapserver/0500_mapserver/sources
  layers/layer3_mapserver/Makefile
Labels: Status: Review Needed

#56 fix: depency issue with new mapserver subpackage
  adm2/_metwork.spec
Labels: Status: Review Needed

#52 feat: we increase some system limits (nofile and nproc)
  adm2/_metwork.spec
Labels: Status: Revision Needed

#57 build: add some additional sources for vim as we have problem with main
  layers/layer7_python2_devtools/0020_vim/sources
  layers/layer7_python3_devtools/0020_vim/sources
Labels: Status: Review Needed

#59 build: add a FORCED_OS_VERSION parameter
  .drone.yml
Labels: Status: Review Needed

#61 build: fix a spec issue with new system limits
  adm2/_metwork.spec
Labels: Status: Review Needed

#69 feat: load mapserver layer by default (if available)
  layers/layer9_default/.layerapi2_dependencies
Labels: Status: Review Needed

#67 doc: add some documentation
  .metwork-framework/README.md
Labels: Status: Review Needed

#68 feat: we can now use plugin_env function in a plugin directory
  adm2/templates/bash_profile
  adm2/templates/interactive_profile
Labels: Status: Review Needed

#71 build: ignore .metwork-framework directory from cache hash
  adm2/_build_cache_hash.sh
Labels: Status: Review Needed
