Repository metwork-framework/mfext, pull requests merged in 2018-12, with the labels that each got.

#134 build: build fix
  adm2/templates/profile
Labels: Merge Now, Status: Pending

#138 fix: mapserverapi upgrade (0.1.0 => 0.1.1)
  layers/layer3_mapserver/0600_mapserverapi/Makefile.mk
  layers/layer3_mapserver/0600_mapserverapi/sources
Labels: Merge Now, Status: Review Needed

#141 feat: telegraf is now monitoring itself
  adm2/templates/telegraf.conf
Labels: Status: Review Needed

#145 fix: fix layer dependencies in new tests
  integration_tests/0004_test_import_python2/.layerapi2_dependencies
  integration_tests/0004_test_import_python3/.layerapi2_dependencies
Labels: Status: Review Needed

#144 feat: telegraf update (1.7.1 => 1.7.4)
  layers/layer0_core/0300_telegraf/Makefile.mk
  layers/layer0_core/0300_telegraf/sources
Labels: Status: Review Needed

#147 feat: add lib, local/lib to `PYTHONPATH` by default (layers, plugins...)
  layerapi2/layer.c
Labels: Merge Now, Status: Review Needed

#150 feat: expose new function in layerapi2
  layerapi2/layer.h
  layerapi2/layerapi2.c
  layerapi2/layerapi2.h
Labels: Merge Now, Status: Review Needed

#149 build: add basic integration test for Fiona
  integration_tests/0003_test_import_python2_scientific/test_import_python2_scientific.py
  integration_tests/0003_test_import_python3_scientific/test_import_python3_scientific.py
Labels: Merge Now, Status: Review Needed

#153 Revert "feat: add lib, local/lib to `PYTHONPATH` by default (layers, …
  layerapi2/layer.c
Labels: Status: Review Needed

#154 build: fix build issue (typo)
  layers/layer4_python2_scientific/0502_Fiona/Makefile.mk
  layers/layer4_python3_scientific/0502_Fiona/Makefile.mk
Labels: Merge Now, Status: Pending

#151 refactor: use the new plugin_wrapper
  adm2/templates/interactive_profile
Labels: Merge Now, Status: Pending

#152 build: add a new watcher in circus template
  adm2/templates/circus.ini
Labels: Merge Now, Status: Pending

#158 feat: add openjdk as a non default layer
  adm2/_metwork.spec
  layers/layer8_java/.layerapi2_dependencies
  layers/layer8_java/.layerapi2_extra_env
  layers/layer8_java/.layerapi2_label
  layers/layer8_java/0500_openjdk/Makefile
  layers/layer8_java/0500_openjdk/Makefile.mk
  layers/layer8_java/0500_openjdk/sources
  layers/layer8_java/Makefile
Labels: Status: Review Needed

#156 build: use sqlite.org official download link
  layers/layer0_core/0020_sqlite/Makefile.mk
  layers/layer0_core/0020_sqlite/sources
Labels: Merge Now, Status: Pending

#157 build: use liquidprompt official latest release
  layers/layer0_core/0010_liquidprompt/Makefile.mk
  layers/layer0_core/0010_liquidprompt/sources
Labels: Merge Now, Status: Pending

#163 feat: upgrade netCDF4 python from 1.4.0 to 1.4.2
  layers/layer4_python2_scientific/0500_extra_packages/requirements2.txt
  layers/layer4_python3_scientific/0500_extra_packages/requirements3.txt
Labels: Status: Pending

#165 build: metwork specfile template evolution according to #160
  adm2/_metwork.spec
Labels: Merge Now, Status: Revision Needed

#166 build: fix specfile template to ignore dependency "python"
  adm2/_metwork.spec
Labels: Merge Now, Status: Review Needed

#167 build: fix template specfile when module has only root layer
  adm2/_metwork.spec
Labels: Status: Review Needed
