Repository metwork-framework/mfext, pull requests merged in 2019-09, with the labels that each got.

#470 build: fix packaging
  adm/_metwork.spec
Labels: Merge Now

#471 build: fix a dependency of the full package
  adm/_metwork.spec
Labels: Merge Now, Status: Review Needed

#469 doc: remove duplicate reference documentation
  .metwork-framework/README.md
Labels: Merge Now, Status: Review Needed

#472 chore: suspicious dependencies and system extra dependencies tests ar…
  integration_tests/0005_suspicious_dependencies/test.sh
  integration_tests/0006_system_extra_dependencies/list.txt
  integration_tests/0006_system_extra_dependencies/test.sh
  layers/layer7_devtools/0000_adm/Makefile.mk
  layers/layer7_devtools/0000_adm/external_dependencies.sh
  layers/layer7_devtools/0000_adm/revert_ldd.sh
Labels: Merge Now, Status: Review Needed

#466 build: add missing pixman dependency since we removed pango
  layers/layer1_scientific_core/.system_dependencies
Labels: Merge Now, Status: Review Needed

#473 build: update openjdk download sources
  layers/layer8_java/0500_openjdk/sources
Labels: Merge Now, Status: Review Needed

#474 doc: better doc
  .gitignore
  adm/Makefile
  adm/_doc_layer.sh
  adm/_generate_full_components_list.sh
  adm/_packaging_get_package_name
  adm/_yaml_to_md.py
  adm/outside
  adm/templates/layer.md
  doc/Makefile
  doc/README.md
  doc/index.rst
  doc/layer_root_custom.md
  doc/layerapi2.md
  doc/layers.rst
  doc/todo.rst
  documented_utilities
  layer_custom.md
  layers/layer0_core/layer_custom.md
  layers/layer0_tcltk/layer_custom.md
  layers/layer1_python2_core/0000_adm/python3_wrapper
  layers/layer1_python2_core/documented_utilities
  layers/layer1_python2_core/layer_custom.md
  layers/layer1_python3_core/0000_adm/python2_wrapper
  layers/layer1_python3_core/layer_custom.md
  layers/layer7_devtools/layer_custom.md
Labels: Merge Now, Status: Review Needed

#475 build: try to add a component list to README
  .metwork-framework/components.md
Labels: Merge Now, Status: Review Needed

#476 build: better components list
  .metwork-framework/components.md
Labels: Merge Now

#477 build: improve generic builds
  adm/_metwork.spec
  adm/_yaml_to_md.py
  adm/main_root.mk
  layers/layer0_core/.system_dependencies
Labels: Merge Now, Status: Review Needed

#478 feat: add some system dependencies
  layers/layer9_default/.system_dependencies
Labels: Merge Now, Status: Review Needed

#480 build: preparing shared doc conf from resources
  doc/Makefile
  doc/Makefile.mk
  doc/README.md
Labels: Merge Now

#481 build: some doc generation improvements
  .gitignore
  adm/_yaml_to_md.py
  adm/main_root.mk
  doc/Makefile.mk
Labels: Merge Now, Status: Review Needed

#482 build: fix system dependency for generic builds
  layers/layer0_core/layer_custom.md
  layers/layer1_scientific_core/.system_dependencies
Labels: Merge Now

#483 build: better doc build
  adm/_yaml_to_md.py
  adm/main_root.mk
Labels: Merge Now, Status: Review Needed

#486 build: fix gdal build to use built-in libpng
  layers/layer1_scientific_core/0023_gdal/Makefile.mk
Labels: Merge Now, Status: Review Needed

#488 build: fix integration tests on centos6
  layers/layer9_default/.system_dependencies
Labels: Status: Review Needed

#490 feat: replace MODULE* environment variables names by MFMODULE* (MODUL…
  .metwork-framework/components.md
  .metwork-framework/configure_a_metwork_package.md
  .metwork-framework/install_a_metwork_package.md
  README.md
  adm/_cache_logic_before_layer.sh
  adm/_cache_path.sh
  adm/_check_layers_hash
  adm/_doc_layer.sh
  adm/_metwork.spec
  adm/_packaging_get_layer_dependencies
  adm/_packaging_get_module_dependencies
  adm/_packaging_get_module_layers
  adm/_packaging_get_package_name
  adm/_yaml_to_md.py
  adm/bash_utils.sh
  adm/main_root.mk
  adm/metwork_debug
  adm/module_hash
  adm/subdir_root.mk
  adm/templates/bash_profile
  adm/templates/bashrc
  adm/templates/circus.ini
  adm/templates/config_profile
  adm/templates/crontab
  adm/templates/cronwrap.sh
  adm/templates/interactive_profile
  adm/templates/layer.md
  adm/templates/load_env.sh
  adm/templates/logrotate.conf
  adm/templates/mfxxx.autorestart
  adm/templates/mfxxx.init
  adm/templates/mfxxx.start
  adm/templates/mfxxx.status
  adm/templates/mfxxx.stop
  adm/templates/mfxxx_wrapper
  adm/templates/nethard_profile
  adm/templates/profile
  adm/templates/telegraf.conf
  bootstrap.sh
  doc/layerapi2.md
  layers/_download_helper.sh
  layers/core_layer.mk
  layers/layer.mk
  layers/layer1_python3_core/0000_adm/install_requirements
Labels: Merge Now, Status: Revision Needed

#493 build: fix systemd behaviour during uninstall
  adm/_metwork.spec
Labels: Merge Now, Status: Review Needed

#495 feat: introduce components utility
  .metwork-framework/README.md
  .metwork-framework/components.md
  adm/Makefile
  adm/_yaml_to_md.py
  adm/components
  doc/layer_root_custom.md
  layers/layer2_python2/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer2_python2/0500_extra_python_packages/requirements2.txt
  layers/layer2_python3/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
  layers/layer7_python3_devtools/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer7_python3_devtools/0500_extra_python_packages/requirements3.txt
Labels: Status: Review Needed

#497 feat: introduce components utility
  adm/Makefile
  adm/components
  layers/layer2_python2/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer2_python2/0500_extra_python_packages/requirements2.txt
  layers/layer2_python3/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
  layers/layer7_python3_devtools/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer7_python3_devtools/0500_extra_python_packages/requirements3.txt
Labels: Merge Now, Status: Review Needed

#498 chore: update mflog version
  layers/layer2_python2/0500_extra_python_packages/requirements2.txt
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Status: Review Needed

#499 feat: add black python component
  .metwork-framework/components.md
  layers/layer7_python3_devtools/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer7_python3_devtools/0500_extra_python_packages/requirements3.txt
Labels: Status: Review Needed

#500 build: remove dummy root layer
  adm/_metwork.spec
Labels: Merge Now, Status: Review Needed

#501 feat: add hmac openresty component
  layers/layer1_openresty/0430_lua_resty_hmac/Makefile
  layers/layer1_openresty/0430_lua_resty_hmac/sources
Labels: Merge Now, Status: Review Needed, backport-to-0.8

#503 build: fix root layer drop
  adm/_metwork.spec
Labels: Merge Now, Status: Review Needed

#504 Update README.md
  .metwork-framework/README.md
Labels: Merge Now
