Repository metwork-framework/mfext, pull requests merged in 2019-03, with the labels that each got.

#222 feat: upgrade mflog to latest master
  layers/layer2_python2/0500_extra_python_packages/requirements2.txt
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Merge Now, Status: Review Needed

#223 Mflog update
  layers/layer2_python2/0500_extra_python_packages/requirements2.txt
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Merge Now, Status: Review Needed

#225 feat: introduce mfext addons
  adm/main_root.mk
  adm2/_metwork.spec
  layers/layer.mk
  layers/layer2_python2/0500_extra_python_packages/requirements2.txt
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Merge Now, Status: Review Needed

#224 feat: mflog update (again)
  layers/layer2_python2/0500_extra_python_packages/requirements2.txt
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Status: Review Needed

#226 feat: introduce mfext addons
  adm/main_root.mk
  adm2/_metwork.spec
  layers/layer.mk
Labels: Merge Now, Status: Review Needed

#227 feat: remove python3_ia layer (we are building an dedicated addon for
  layers/layer5_python3_ia/.layerapi2_dependencies
  layers/layer5_python3_ia/.layerapi2_label
  layers/layer5_python3_ia/0500_extra_packages/Makefile
  layers/layer5_python3_ia/0500_extra_packages/Makefile.mk
  layers/layer5_python3_ia/0500_extra_packages/allow_binary_packages
  layers/layer5_python3_ia/0500_extra_packages/prerequirements-to-freeze.txt
  layers/layer5_python3_ia/0500_extra_packages/prerequirements3.txt
  layers/layer5_python3_ia/0500_extra_packages/requirements-to-freeze.txt
  layers/layer5_python3_ia/0500_extra_packages/requirements3.txt
  layers/layer5_python3_ia/Makefile
Labels: Merge Now, Status: Review Needed

#230 build: rpm epoch bump
  adm/main_root.mk
Labels: Status: Review Needed

#229 refactor: expose an unsafe_pip command (for manual use) and use it
  layers/layer1_python2_core/0000_adm/Makefile.mk
  layers/layer1_python2_core/0000_adm/unsafe_pip
  layers/layer1_python3_core/0000_adm/Makefile.mk
  layers/layer1_python3_core/0000_adm/download_compile_requirements
  layers/layer1_python3_core/0000_adm/freeze_requirements
  layers/layer1_python3_core/0000_adm/install_requirements
  layers/layer1_python3_core/0000_adm/unsafe_pip
Labels: Status: Review Needed

#233 feat: delete filebeat component
  layers/layer8_monitoring/0400_filebeat/Makefile
  layers/layer8_monitoring/0400_filebeat/Makefile.mk
  layers/layer8_monitoring/0400_filebeat/sources
Labels: Status: Review Needed

#234 fix: fix mfxxx.start/stop/status when used in some special dirs
  adm2/templates/mfxxx.init
  adm2/templates/mfxxx.start
  adm2/templates/mfxxx.status
  adm2/templates/mfxxx.stop
Labels: Status: Review Needed

#237 feat: add a first version of jsonlog2elasticsearch
  .gitignore
  layers/layer8_monitoring/.layerapi2_dependencies
  layers/layer8_monitoring/0500_extra_packages/Makefile
  layers/layer8_monitoring/0500_extra_packages/Makefile.mk
  layers/layer8_monitoring/0500_extra_packages/prerequirements-to-freeze.txt
  layers/layer8_monitoring/0500_extra_packages/prerequirements3.txt
  layers/layer8_monitoring/0500_extra_packages/requirements-to-freeze.txt
  layers/layer8_monitoring/0500_extra_packages/requirements3.txt
Labels: Status: Review Needed

#239 fix: fix some installation issues in some corner cases
  adm2/_metwork.spec
Labels: Merge Now

#238 feat: add sphinx-automodapi module
  layers/layer7_python3_devtools/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer7_python3_devtools/0500_extra_python_packages/requirements3.txt
Labels: Status: Review Needed

#242 Buildfix3
  layers/layer8_monitoring/0500_extra_packages/requirements3.txt
Labels: Merge Now, Status: Review Needed

#241 build: fix layer root branch when branch is not integration or master
  adm2/_metwork.spec
Labels: Status: Review Needed

#246 Ci mfutil c
  .gitignore
  Makefile
  adm/_prelayers_hash.sh
  adm/bash_utils.sh
  mfutil_c/Makefile
  mfutil_c/sources
Labels: Merge Now, Status: Review Needed

#249 Mflog update3
  layers/layer2_python2/0500_extra_python_packages/requirements2.txt
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Status: Review Needed

#170 [WIP] refactor: little change for conditional init in mfadmin
  adm2/templates/mfxxx.start
Labels: Merge Now, Status: Review Needed

#252 feat: refuse mfxxx.stop/start if the config.ini is newer than the cur…
  adm2/templates/mfxxx.start
  adm2/templates/mfxxx.status
  adm2/templates/mfxxx.stop
Labels: Status: Review Needed

#253 fix: upgrade problems at RPM levels
  adm2/_metwork.spec
Labels: Status: Review Needed

#256 fix: fix some rpm upgrades
  adm2/_metwork.spec
Labels: Merge Now, Status: Review Needed

#258 build: mflog update (again)
  layers/layer2_python2/0500_extra_python_packages/requirements2.txt
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Merge Now

#260 feat: try to keep a backup of user files during uninstall
  adm2/_metwork.spec
Labels: Merge Now
