Repository metwork-framework/mfext, pull requests merged in 2019-02, with the labels that each got.

#198 [WIP] feat: introduce new mflog library
  layers/layer2_python2/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer2_python2/0500_extra_python_packages/requirements2.txt
  layers/layer2_python3/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Merge Now, Status: Review Needed

#202 build: fix outside build
  adm2/outside
Labels: Merge Now, Status: Review Needed, backport-to-0.5

#205 feat: Upgrade geos from 3.6.2 to 3.7.1 (with scl for C++11 on centos6)
  layers/layer1_scientific/0021_geos/Makefile.mk
  layers/layer1_scientific/0021_geos/sources
Labels: Status: Review Needed

#207 refactor: changes for the new mflog lib
  adm2/templates/circus.ini
  adm2/templates/profile
  layers/layer2_python2/0500_extra_python_packages/requirements2.txt
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Merge Now, Status: Review Needed

#209 fix: rpm names with release tags
  adm2/_metwork.spec
Labels: Merge Now, backport-to-0.5

#208 fix: force epoch=1 in centos7 openssl dependency
  adm2/_metwork.spec
Labels: Status: Review Needed, backport-to-0.5

#206 feat: Upgrade postgis from 2.4.4 to 2.4.6
  layers/layer1_scientific/0070_postgis/Makefile.mk
  layers/layer1_scientific/0070_postgis/sources
Labels: Status: Review Needed, backport-to-0.5

#212 fix: obsoletes wrong named packages
  adm2/_metwork.spec
Labels: Merge Now, Status: Review Needed

#218 fix: mapserverapi update (0.1.2 => 0.1.3)
  layers/layer3_mapserver/0600_mapserverapi/Makefile.mk
  layers/layer3_mapserver/0600_mapserverapi/sources
Labels: Merge Now, Status: Review Needed, backport-to-0.5

#220 Issue31
  adm2/_metwork.spec
Labels: Merge Now, backport-to-0.5
