Repository metwork-framework/mfext, pull requests merged in 2019-04, with the labels that each got.

#265 build: fix glib2 update
  glib2/Makefile
Labels: Merge Now

#267 build: bump epoch
  adm/main_root.mk
Labels: Merge Now

#268 build: tmp obsoletes mfext metapackages
  adm2/_metwork.spec
Labels: Merge Now, Status: Review Needed

#269 build: typo
  adm2/_metwork.spec
Labels: Merge Now

#271 build: remove numpy from mfext (will be transferred to
  layers/layer2_python2/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer2_python2/0500_extra_python_packages/requirements2.txt
  layers/layer2_python3/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Status: Review Needed

#272 feat: introduce mflog2mfadmin feature
  adm2/templates/circus.ini
Labels: Merge Now

#273 build: build fix (numpy integration test must be deleted here)
  integration_tests/0004_test_import_python3/import_python3.py
Labels: Merge Now

#274 feat: mflog update
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Merge Now

#275 fix: fix the making of circus.ini from template on mfadmin (mfadmin.s…
  adm2/templates/circus.ini
Labels: Merge Now, Status: Review Needed

#278 fix: only the layers corresponding to the current addon should be in the
  adm/main_root.mk
  adm2/_metwork.spec
Labels: Merge Now

#279 fix: upgrade mflog to fix metwork-framework/mflog#8
  layers/layer2_python2/0500_extra_python_packages/requirements2.txt
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Status: Review Needed, backport-to-0.6

#280 fix: more reliable checks about some circus watchers
  adm2/templates/mfxxx.start
  adm2/templates/mfxxx.status
Labels: Status: Review Needed

#282 build: add a download mirror for sloccount
  layers/layer7_devtools/0040_sloccount/sources
Labels: Status: Review Needed

#286 feat: update mflog and use new automatic context function
  adm2/templates/profile
  layers/layer2_python2/0500_extra_python_packages/requirements2.txt
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Status: Review Needed

#287 feat: remove prerequirements files
  layers/layer2_python2/0499_prereq_extra_python_packages/prerequirements-to-freeze.txt
  layers/layer2_python2/0499_prereq_extra_python_packages/prerequirements2.txt
  layers/layer2_python2/0500_extra_python_packages/prerequirements-to-freeze.txt
  layers/layer2_python2/0500_extra_python_packages/prerequirements2.txt
  layers/layer2_python3/0499_prereq_extra_python_packages/prerequirements-to-freeze.txt
  layers/layer2_python3/0499_prereq_extra_python_packages/prerequirements3.txt
  layers/layer2_python3/0500_extra_python_packages/prerequirements-to-freeze.txt
  layers/layer2_python3/0500_extra_python_packages/prerequirements3.txt
  layers/layer2_python3_circus/0500_circus/prerequirements-to-freeze.txt
  layers/layer2_python3_circus/0500_circus/prerequirements3.txt
  layers/layer7_python2_devtools/0499_prereq_extra_python_packages/prerequirements-to-freeze.txt
  layers/layer7_python2_devtools/0499_prereq_extra_python_packages/prerequirements2.txt
  layers/layer7_python2_devtools/0500_extra_python_packages/prerequirements-to-freeze.txt
  layers/layer7_python2_devtools/0500_extra_python_packages/prerequirements2.txt
  layers/layer7_python3_devtools/0499_prereq_extra_python_packages/prerequirements-to-freeze.txt
  layers/layer7_python3_devtools/0499_prereq_extra_python_packages/prerequirements3.txt
  layers/layer7_python3_devtools/0500_extra_python_packages/prerequirements-to-freeze.txt
  layers/layer7_python3_devtools/0500_extra_python_packages/prerequirements3.txt
  layers/layer7_python3_devtools_jupyter/0500_extra_python_packages/prerequirements-to-freeze.txt
  layers/layer7_python3_devtools_jupyter/0500_extra_python_packages/prerequirements3.txt
  layers/layer8_monitoring/0500_extra_packages/prerequirements-to-freeze.txt
  layers/layer8_monitoring/0500_extra_packages/prerequirements3.txt
  layers/python_layer.mk
Labels: Merge Now

#288 feat: update mflog
  layers/layer2_python2/0500_extra_python_packages/requirements2.txt
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Merge Now, Status: Review Needed

#289 fix: backport of #279 to fix metwork-framework/mflog#8
  layers/layer2_python2/0500_extra_python_packages/requirements2.txt
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Status: Review Needed

#290 build: mflog update (fix latest commit)
  layers/layer2_python2/0500_extra_python_packages/requirements2.txt
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Merge Now, Status: Review Needed

#291 build: fix latest commit
  layers/layer2_python2/0500_extra_python_packages/requirements2.txt
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Merge Now, Status: Review Needed

#292 fix: don't launch mflog2mfadmin is admin hostname is null
  adm2/templates/mfxxx.start
Labels: Merge Now

#294 refactor: each single layer rpm of a branch now provides the same single
  adm2/_metwork.spec
Labels: Status: Review Needed

#295 docs: Update MFEXT documentation
  .metwork-framework/README.md
  adm2/_yaml_to_md.py
  adm2/templates/layer.md
  doc/Makefile
  doc/_static/css/override_theme.css
  doc/_templates/breadcrumbs.html
  doc/_templates/layout.html
  doc/conf.py
  doc/images/logo-metwork.png
  doc/images/metwork.ico
  doc/index.rst
  doc/layerapi2.md
Labels: Status: Review Needed

#296 build: clean some old things
  adm/main_root.mk
  adm2/templates/bootstrap.sh
  adm2/templates/doc/Makefile
  adm2/templates/doc/conf.py
Labels: Merge Now, Status: Review Needed

#297 feat: add graphviz in devtools layer (for documentation)
  layers/layer7_devtools/0050_graphviz/Makefile
  layers/layer7_devtools/0050_graphviz/Makefile.mk
  layers/layer7_devtools/0050_graphviz/sources
Labels: Merge Now, Status: Review Needed

#300 feat: remove support gdk, gtk and qt from graphviz
  layers/layer7_devtools/0050_graphviz/Makefile.mk
Labels: Status: Review Needed

#303 fix: jinja2 update (security) 2.10 => 2.10.1
  layers/layer2_python2/0500_extra_python_packages/requirements2.txt
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Merge Now, Status: Review Needed, backport-to-0.5, backport-to-0.6

#306 feat: allow to build mfext behing a corporate http proxy
  adm/Makefile
  adm/_proxy_set.sh
  layers/_download_helper.sh
  layers/core_layer.mk
  layers/layer1_python3_core/0000_adm/install_requirements
  layers/layer8_nodejs/0600_npm/Makefile.mk
  layers/python_layer.mk
Labels: Merge Now, Status: Review Needed

#308 Proxy
  adm/_proxy_set.sh
  bootstrap.sh
  layers/_download_helper.sh
  layers/core_layer.mk
  layers/layer1_python3_core/0000_adm/install_requirements
  layers/layer8_nodejs/0600_npm/Makefile.mk
  layers/python_layer.mk
Labels: Merge Now, Status: Review Needed

#309 feat: add search_paths feature to cookiecutter
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Merge Now

#307 feat: urllib3 update (1.23 => 1.24.2) because of upstream security issue
  layers/layer2_python2/0500_extra_python_packages/requirements2.txt
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Merge Now, Status: Review Needed, backport-to-0.6

#311 docs: Update MFEXT documentation
  .gitignore
  adm2/_yaml_to_md.py
  adm2/templates/layer.md
  doc/Makefile
  doc/changelogs.rst
  doc/index.rst
  doc/todo.rst
  doc/tutorial_layerapi2.ipynb
  layer_custom.md
  layers/layer0_core/0029_curl/Makefile.mk
  layers/layer1_python2_core/0030_python2/Makefile.mk
  layers/layer1_python2_core/0041_six/Makefile.mk
  layers/layer1_python2_core/0042_appdirs/Makefile.mk
  layers/layer1_python2_core/0045_setuptools/Makefile.mk
  layers/layer1_python2_core/layer_custom.md
  layers/layer1_python3_core/0040_python3/Makefile.mk
  layers/layer1_python3_core/0041_six/Makefile.mk
  layers/layer1_python3_core/0042_appdirs/Makefile.mk
  layers/layer1_python3_core/0045_setuptools/Makefile.mk
  layers/layer1_python3_core/layer_custom.md
  layers/layer1_rpm/0135_db/Makefile.mk
  layers/layer1_rpm/layer_custom.md
  layers/layer1_scientific_core/0020_proj4/Makefile.mk
  layers/layer1_scientific_core/0021_geos/Makefile.mk
  layers/layer1_scientific_core/0022_gdal/Makefile.mk
  layers/layer1_scientific_core/0025_cairo/Makefile.mk
  layers/layer1_scientific_core/layer_custom.md
  layers/layer2_python2/layer_custom.md
  layers/layer2_python3/layer_custom.md
  layers/layer2_python3_circus/layer_custom.md
  layers/layer7_devtools/layer_custom.md
  layers/layer7_python2_devtools/layer_custom.md
  layers/layer7_python3_devtools/layer_custom.md
  layers/layer7_python3_devtools_jupyter/layer_custom.md
  layers/layer8_java/layer_custom.md
  layers/layer8_monitoring/layer_custom.md
  layers/layer8_nodejs/0500_nodejs/Makefile.mk
  layers/layer8_nodejs/layer_custom.md
  layers/layer9_default/layer_custom.md
  layers/layer9_python/layer_custom.md
Labels: Status: Review Needed

#312 feat: add cookiecutter_hooks project
  adm/subdir_root.mk
  layers/layer2_python3/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Merge Now, Status: Review Needed

#313 build: update cookiecutter_hooks
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Merge Now, Status: Review Needed

#314 docs: Update MFEXT documentation
  doc/layerapi2.md
  documented_utilities
  layer_custom.md
Labels: Merge Now, Status: Review Needed

#316 feat: update openjdk 11.0.1 => 11.0.2 and add mirror
  layers/layer8_java/0500_openjdk/Makefile.mk
  layers/layer8_java/0500_openjdk/sources
Labels: Merge Now, Status: Review Needed
