Repository metwork-framework/mfext, pull requests merged in 2019-12, with the labels that each got.

#591 build: Uggly work-around waiting eccodes to build with openjpeg > 2.1
  layers/layer1_scientific_core/0005_openjpeg/Makefile.mk
Labels: Status: Review Needed

#603 feat: upgrade postgresql from 10.11 to 12.1 and postgis from 2.4.6 to…
  .metwork-framework/components.md
  layers/layer1_scientific_core/0008_postgresql/Makefile.mk
  layers/layer1_scientific_core/0008_postgresql/sources
  layers/layer1_scientific_core/0070_postgis/Makefile.mk
  layers/layer1_scientific_core/0070_postgis/sources
Labels: Status: Review Needed

#606 build: fix make clean target
  layers/layer9_python2_misc/0500_mflog_addon/Makefile.mk
  layers/layer9_python3_misc/0300_circus_hooks/Makefile.mk
  layers/layer9_python3_misc/0300_conf_monitor/Makefile.mk
  layers/layer9_python3_misc/0400_jsonlog2elasticsearch_metwork_addon/Makefile.mk
  layers/layer9_python3_misc/0500_mflog_addon/Makefile.mk
Labels: Status: Review Needed

#608 Update centos8
  .metwork-framework/components.md
  layers/layer1_scientific_core/0024_pixman/Makefile
  layers/layer1_scientific_core/0024_pixman/Makefile.mk
  layers/layer1_scientific_core/0024_pixman/sources
  layers/layer1_scientific_core/0025_cairo/Makefile.mk
  layers/layer1_scientific_core/0025_cairo/sources
  layers/layer1_scientific_core/0070_postgis/Makefile.mk
Labels: Status: Review Needed

#607 Prepare
  adm/_make_file_from_template.sh
  adm/config_subdir.mk
  adm/templates/config.ini
Labels: Status: Review Needed

#609 feat: add json2syslog2elasticsearch
  layers/layer8_monitoring/0500_extra_packages/requirements-to-freeze.txt
  layers/layer8_monitoring/0500_extra_packages/requirements3.txt
Labels: Status: Review Needed

#610 build: fix pr #609
  layers/layer8_monitoring/0500_extra_packages/requirements3.txt
Labels: Merge Now, Status: Review Needed

#611 build: fix pr #609
  .metwork-framework/components.md
Labels: Merge Now, Status: Review Needed

#612 build: fix pr #609
  .metwork-framework/components.md
Labels: Merge Now, Status: Review Needed

#614 Update centos8
  layers/layer7_devtools/0030_ack/Makefile.mk
  layers/layer7_devtools/0030_ack/sources
  layers/layer7_devtools/0030_the_silver_searcher/Makefile
  layers/layer7_devtools/0030_the_silver_searcher/Makefile.mk
  layers/layer7_devtools/0030_the_silver_searcher/no_lzma.patch
  layers/layer7_devtools/0030_the_silver_searcher/patches
  layers/layer7_devtools/0030_the_silver_searcher/sources
  layers/layer8_nodejs/0500_nodejs/Makefile.mk
  layers/layer8_nodejs/0500_nodejs/sources
Labels: Status: Review Needed

#613 feat: add log_proxy
  layers/layer0_core/0080_log_proxy/Makefile
  layers/layer0_core/0080_log_proxy/Makefile.mk
  layers/layer0_core/0080_log_proxy/sources
Labels: Status: Review Needed

#616 build: update components.md
  .metwork-framework/components.md
Labels: Merge Now, Status: Review Needed

#617 build: update components.md
  .metwork-framework/components.md
Labels: Merge Now, Status: Review Needed

#619 feat: update circus_autorestart_plugin
  layers/layer2_python3_circus/0500_circus/requirements3.txt
Labels: Merge Now, Status: Review Needed, backport-to-0.9
