Repository metwork-framework/mfext, pull requests merged in 2019-08, with the labels that each got.

#408 feat: add revert_ldd.sh and external_dependencies.sh utilities
  layers/layer7_devtools/0000_adm/Makefile.mk
  layers/layer7_devtools/0000_adm/external_dependencies.sh
  layers/layer7_devtools/0000_adm/revert_ldd.sh
Labels: Merge Now, Status: Review Needed

#410 feat: mflog update to support non standard logging levels
  layers/layer2_python2/0500_extra_python_packages/requirements2.txt
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Merge Now, Status: Review Needed, backport-to-0.7

#409 test: add a suspicious dependencies test
  integration_tests/0005_suspicious_dependencies/test.sh
  layers/layer7_devtools/0050_graphviz/Makefile.mk
Labels: Merge Now, Status: Review Needed

#417 build: ignore plugin files in dhash
  config/dhash_ignore_all
Labels: Merge Now, Status: Revision Needed

#415 feat: update mfutil_c and introduce mfutil_lua
  layers/layer1_openresty/0500_mfutil_lua/Makefile
  layers/layer1_openresty/0500_mfutil_lua/Makefile.mk
  layers/layer1_openresty/0500_mfutil_lua/sources
  mfutil_c/Makefile
  mfutil_c/sources
Labels: Merge Now, Status: Review Needed

#414 Backport410
  layers/layer2_python2/0500_extra_python_packages/requirements2.txt
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Merge Now, Status: Review Needed

#418 build: fix some weird python compilation issues in scientific addon
  layers/layer1_python3_core/0000_adm/download_compile_requirements
Labels: Merge Now, Status: Review Needed

#419 build: fix build with python2
  layers/layer1_python3_core/0000_adm/download_compile_requirements
Labels: Merge Now, Status: Review Needed

#421 doc: better readme
  .gitignore
  .metwork-framework/README.md
  doc/Makefile
  doc/README.md
  layers/layer7_devtools/0021_configvim/Makefile.mk
  layers/layer7_devtools/0021_configvim/vimrc
Labels: Merge Now, Status: Review Needed

#422 build: use rpath for mfutil_c
  mfutil_c/Makefile
  mfutil_c/sources
Labels: Merge Now, Status: Review Needed

#423 build: fix mfutil location since mfext migration
  layers/layer1_openresty/0500_mfutil_lua/Makefile.mk
Labels: Merge Now, Status: Review Needed

#424 build: little fix about mfutil_c migration from mfcom to mfext
  adm/templates/interactive_profile
Labels: Merge Now, Status: Review Needed

#425 build: cache path fix
  adm/_cache_path.sh
Labels: Merge Now, Status: Review Needed, backport-to-0.8

#429 build: add an integration test about extra system dependencies
  integration_tests/0006_system_dependencies/test.sh
Labels: Merge Now, Status: Review Needed

#428 Update _vim_wrapper.sh
  wrappers/_vim_wrapper.sh
Labels: Merge Now, Status: Review Needed

#433 build: execute extra dep test only on centos6
  integration_tests/0006_system_extra_dependencies/test.sh
Labels: Merge Now, Status: Review Needed

#435 build: update extra deps
  integration_tests/0006_system_extra_dependencies/list.txt
  integration_tests/0006_system_extra_dependencies/test.sh
Labels: Merge Now

#440 build: try to fix update problems
  adm/_metwork.spec
Labels: Merge Now, Status: Review Needed

#439 build: fix download address for openjdk 11.0.2
  layers/layer8_java/0500_openjdk/Makefile.mk
  layers/layer8_java/0500_openjdk/sources
Labels: Merge Now, Status: Review Needed

#434 feat: introduce build extra dependencies
  layers/layer_wrapper.mk
Labels: Merge Now, Status: Review Needed

#427 feat: upgrade netcdf and build with gcc/gfortran >= 4.5 for fortran c…
  layers/layer1_scientific_core/0012_netcdf_c/Makefile.mk
  layers/layer1_scientific_core/0012_netcdf_c/sources
  layers/layer1_scientific_core/0013_netcdf_cxx/Makefile.mk
  layers/layer1_scientific_core/0014_netcdf_fortran/Makefile.mk
  layers/layer1_scientific_core/0014_netcdf_fortran/sources
Labels: Merge Now, Status: Review Needed

#444 fix: fix vi usage without devtools
  wrappers/_vim_wrapper.sh
Labels: Merge Now, Status: Review Needed, backport-to-0.8

#447 build: fix rpm update issue with new packaging
  adm/_metwork.spec
Labels: Merge Now, Status: Review Needed

#441 feat: embed libffi and use it instead of system library
  .gitignore
  Makefile
  layers/layer1_python2_core/0030_python2/Makefile.mk
  layers/layer1_python3_core/0030_python3/Makefile.mk
  libffi/Makefile
  libffi/libffi_build.patch
  libffi/patches
  libffi/sources
Labels: Merge Now, Status: Review Needed

#442 doc: readme update
  .gitignore
  .metwork-framework/README.md
  adm/Makefile
  adm/_generate_full_components_list.sh
  adm/_yaml_to_md.py
  doc/Makefile
  doc/index.rst
Labels: Merge Now, Status: Review Needed

#449 doc: doc fix
  doc/Makefile
Labels: Merge Now, Status: Review Needed

#448 fix: use vi in python2 mode when we are in python2
  wrappers/_vim_wrapper.sh
  wrappers/_vimdiff_wrapper.sh
Labels: Merge Now, Status: Review Needed, backport-to-0.8

#451 doc: fix doc build (again)
  doc/Makefile
Labels: Merge Now

#452 fix: fix issue #35 on addon scientific (build problem with python2 ESMF)
  layers/layer1_scientific_core/.system_dependencies
Labels: Merge Now

#453 feat: embed readline and use it instead of the system library
  layers/layer0_core/0005_readline/Makefile
  layers/layer0_core/0005_readline/Makefile.mk
  layers/layer0_core/0005_readline/patches
  layers/layer0_core/0005_readline/readline-link-to-libtinfo.patch
  layers/layer0_core/0005_readline/sources
  layers/layer0_core/0020_sqlite/Makefile.mk
Labels: Merge Now

#455 Remove system dependencies libgfortran, libgfortran4 and libpng12
  layers/Makefile.standard
  layers/layer1_scientific_core/.system_dependencies
  layers/layer1_scientific_core/0003_libpng/Makefile
  layers/layer1_scientific_core/0003_libpng/Makefile.mk
  layers/layer1_scientific_core/0003_libpng/sources
  layers/layer1_scientific_core/0012_netcdf_c/Makefile.mk
  layers/layer1_scientific_core/0013_netcdf_cxx/Makefile.mk
  layers/layer1_scientific_core/0014_netcdf_fortran/Makefile.mk
  layers/layer1_scientific_core/0014_netcdf_fortran/sources
Labels: Status: Review Needed

#458 build: fix download source for libev
  layers/layer0_core/0015_libev/sources
Labels: Status: Review Needed

#460 doc: Update README.md
  .metwork-framework/README.md
Labels: Status: Review Needed

#462 build: remove useless system dependencies
  layers/layer1_scientific_core/.system_dependencies
Labels: Merge Now, Status: Review Needed

#459 build: activate test on system extra dependencies (the build fails if…
  integration_tests/0006_system_extra_dependencies/test.sh
Labels: Merge Now, Status: Review Needed

#463 build: fix build target
  layers/layer1_scientific_core/0003_libpng/Makefile.mk
Labels: Merge Now, Status: Review Needed

#464 build: fix build with embedded readline and without system readline-d…
  layers/layer0_core/0020_sqlite/Makefile.mk
Labels: Merge Now, Status: Review Needed

#465 build: add a system dependency for tcl/tk
  layers/layer0_tcltk/.system_dependencies
Labels: Merge Now, Status: Review Needed
