Repository metwork-framework/mfext, pull requests merged in 2019-06, with the labels that each got.

#374 feat: update cookiecutter_hooks (reduce multi blank lines to a single…
  layers/layer2_python3/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Merge Now, Status: Review Needed

#376 fix: add pycodestyle (missing dependency for autopep8)
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Status: Review Needed

#377 fix: add pycodestyle (missing dependency for autopep8)
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Status: Review Needed

#375 docs: generate automatically changelogs entries in changelogs.rst file
  .gitignore
  doc/Makefile
  doc/changelogs.tmpl
Labels: Merge Now, Status: Review Needed

#385 fix: disable SSE4.2 optimizations to avoid nginx crashing on old servers
  layers/layer1_openresty/0100_openresty/github_issue384.patch
  layers/layer1_openresty/0100_openresty/patches
Labels: Status: Review Needed, backport-to-0.7

#390 feat: give up modules start if precondition failed
  adm2/templates/mfxxx.start
Labels: Merge Now, Status: Review Needed, backport-to-0.7

#391 vim config change
  layers/layer7_devtools/0021_configvim/vimrc
Labels: Merge Now, Status: Review Needed
