Repository metwork-framework/mfext, pull requests merged in 2019-01, with the labels that each got.

#140 [WIP] feat: clean some useless files in .plugin files (part1)
  adm2/templates/plugin.spec
Labels: Merge Now, Status: Pending, Status: Review Needed

#173 build: change for new autorestart feature
  adm2/templates/plugin.spec
Labels: Merge Now, Status: Pending, Status: Review Needed

#174 build: move circus_autorestart_plugin to mfext
  layers/layer2_python3_circus/0500_circus/requirements-to-freeze.txt
Labels: Merge Now, Status: Review Needed

#175 build: #174 fix
  layers/layer2_python3_circus/0500_circus/requirements3.txt
Labels: Merge Now, Status: Review Needed

#177 build: add wget as dependency
  adm2/_metwork.spec
Labels: Merge Now, Status: Pending

#176 [wip] feat: upgrade python3 from 3.5.3 to 3.5.6 and python2 from 2.7.9 to
  layers/layer1_python2_core/0030_python2/Makefile.mk
  layers/layer1_python2_core/0030_python2/sources
  layers/layer1_python3_core/0040_python3/Makefile.mk
  layers/layer1_python3_core/0040_python3/sources
Labels: Merge Now, Status: Pending

#181 fix: rpm names was incorrect with release tags
  adm2/_metwork.spec
Labels: Merge Now, Status: Pending, backport-to-0.4

#183 fix: rpm names were incorrect with release tags
  adm2/_metwork.spec
Labels: Merge Now, Status: Pending

#186 fix: do not include .git* files in the plugin RPM
  adm2/templates/plugin.spec
Labels: Status: Pending

#180 build: add DRONE_TAG support
  adm/guess_version.sh
  adm2/_build_cache_hash.sh
Labels: Merge Now, Status: Pending

#179 [WIP] feat: lua-resty-stats upgrade (0.0.2 => 0.0.3)
  layers/layer1_openresty/0420_lua_resty_statsd/Makefile
  layers/layer1_openresty/0420_lua_resty_statsd/sources
Labels: Merge Now, Status: Pending

#185 feat: ignore lines starting with # in .layerapi2_dependencies/conflicts
  layerapi2/tests/lines
  layerapi2/util.c
Labels: Merge Now, Status: Pending

#193 feat: add some metapackages aliases to have a cleaner installation doc
  adm2/_metwork.spec
Labels: Status: Review Needed

#192 feat: we remove the src directory from .plugin files
  adm2/templates/plugin.spec
Labels: Status: Pending

#195 feat: user-defined configuration name
  adm2/templates/profile
Labels: Status: Pending

#196 cleaner plugin file
  adm2/templates/plugin.spec
Labels: Status: Review Needed

#197 [WIP] feat: execute integration tests directly from mfext module
  .drone.yml
  integration_tests/0001_test_python2_sqlite3/python2_sqlite3.py
  integration_tests/0001_test_python2_sqlite3/test_python2_sqlite3.sh
  integration_tests/0001_test_python3_sqlite3/python3_sqlite3.py
  integration_tests/0001_test_python3_sqlite3/test_python3_sqlite3.sh
  integration_tests/0002_test_python2_mapserverapi/datas/ne_110m_land.README.html
  integration_tests/0002_test_python2_mapserverapi/datas/ne_110m_land.VERSION.txt
  integration_tests/0002_test_python2_mapserverapi/datas/ne_110m_land.cpg
  integration_tests/0002_test_python2_mapserverapi/datas/ne_110m_land.dbf
  integration_tests/0002_test_python2_mapserverapi/datas/ne_110m_land.prj
  integration_tests/0002_test_python2_mapserverapi/datas/ne_110m_land.shp
  integration_tests/0002_test_python2_mapserverapi/datas/ne_110m_land.shx
  integration_tests/0002_test_python2_mapserverapi/datas/ne_110m_ocean.README.html
  integration_tests/0002_test_python2_mapserverapi/datas/ne_110m_ocean.VERSION.txt
  integration_tests/0002_test_python2_mapserverapi/datas/ne_110m_ocean.cpg
  integration_tests/0002_test_python2_mapserverapi/datas/ne_110m_ocean.dbf
  integration_tests/0002_test_python2_mapserverapi/datas/ne_110m_ocean.prj
  integration_tests/0002_test_python2_mapserverapi/datas/ne_110m_ocean.shp
  integration_tests/0002_test_python2_mapserverapi/datas/ne_110m_ocean.shx
  integration_tests/0002_test_python2_mapserverapi/datas/test.map
  integration_tests/0002_test_python2_mapserverapi/python2_mapserverapi.py
  integration_tests/0002_test_python2_mapserverapi/test_python2_mapserverapi.sh
  integration_tests/0002_test_python3_mapserverapi/datas
  integration_tests/0002_test_python3_mapserverapi/python3_mapserverapi.py
  integration_tests/0002_test_python3_mapserverapi/test_datas
  integration_tests/0002_test_python3_mapserverapi/test_python3_mapserverapi.sh
  integration_tests/0003_test_import_python2_scientific/import_python2_scientific.py
  integration_tests/0003_test_import_python2_scientific/test_import_python2_scientific.sh
  integration_tests/0003_test_import_python3_scientific/import_python3_scientific.py
  integration_tests/0003_test_import_python3_scientific/test_import_python3_scientific.sh
  integration_tests/0004_test_import_python2/import_python2.py
  integration_tests/0004_test_import_python2/test_import_python2.sh
  integration_tests/0004_test_import_python3/import_python3.py
  integration_tests/0004_test_import_python3/test_import_python3.sh
  run_integration_tests.sh
Labels: Status: Review Needed
