Repository metwork-framework/mfext, pull requests merged in 2019-05, with the labels that each got.

#318 feat: openresty update (1.11.2.2 => 1.13.6.2)
  layers/layer1_openresty/0100_openresty/Makefile.mk
  layers/layer1_openresty/0100_openresty/sources
Labels: Merge Now

#319 fix: update internal circus version to fix a bug with async_kill feature
  layers/layer2_python3_circus/0500_circus/requirements3.txt
Labels: Merge Now, Status: Review Needed

#322 feat: keep request_id field in logs
  adm2/templates/profile
Labels: Merge Now, Status: Review Needed

#321 feat: add sqlite3 and libspatialite supports to gdal
  layers/layer1_scientific_core/0022_libspatialite/Makefile
  layers/layer1_scientific_core/0022_libspatialite/Makefile.mk
  layers/layer1_scientific_core/0022_libspatialite/sources
  layers/layer1_scientific_core/0023_gdal/Makefile
  layers/layer1_scientific_core/0023_gdal/Makefile.mk
  layers/layer1_scientific_core/0023_gdal/sources
Labels: Status: Review Needed

#323 feat: add werkzeug component (python wsgi toolbox)
  layers/layer7_python2_devtools/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer7_python2_devtools/0500_extra_python_packages/requirements2.txt
  layers/layer7_python3_devtools/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer7_python3_devtools/0500_extra_python_packages/requirements3.txt
Labels: Status: Closed

#324 feat: add some sysctl tunings
  adm2/_metwork.spec
Labels: Merge Now, Status: Review Needed

#325 chore: don't use plugin name for building plugin home
  adm2/templates/interactive_profile
Labels: Merge Now, Status: Review Needed

#326 chore: move sysctl_metwork.conf to mfcom
  adm2/_metwork.spec
Labels: Status: Review Needed

#327 build: fix the display of usage message as root (for CI)
  adm2/templates/mfxxx.init
  adm2/templates/mfxxx.start
  adm2/templates/mfxxx.status
  adm2/templates/mfxxx.stop
Labels: Merge Now, Status: Review Needed

#328 feat: add terminaltables component
  layers/layer2_python3/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Status: Review Needed

#331 fix: use python3 to build glib2 python tools and remove references to…
  glib2/Makefile
Labels: Merge Now, Status: Review Needed

#329 feat: restore env after exiting plugin_env
  adm2/templates/interactive_profile
Labels: Merge Now, Status: Review Needed

#332 build: add terminaltables also for python2
  layers/layer2_python2/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer2_python2/0500_extra_python_packages/requirements2.txt
Labels: Merge Now, Status: Review Needed

#333 fix: add a patch for openresty about nginx upstreams
  layers/layer1_openresty/0100_openresty/github_pr67.patch
  layers/layer1_openresty/0100_openresty/patches
Labels: Merge Now, Status: Review Needed

#334 feat: remove layer python
  adm2/_metwork.spec
  adm2/templates/profile
  layers/layer9_default/.layerapi2_dependencies
  layers/layer9_python/.layerapi2_dependencies
  layers/layer9_python/.layerapi2_label
  layers/layer9_python/Makefile
  layers/layer9_python/layer_custom.md
  wrappers/Makefile
  wrappers/flake82.sh
  wrappers/flake83.sh
  wrappers/nosetests2.sh
  wrappers/nosetests3.sh
  wrappers/pylint2.sh
  wrappers/pylint3.sh
Labels: Status: Review Needed

#335 feat: remove layer python
  layers/layer9_default/.layerapi2_dependencies
Labels: Status: Review Needed

#337 docs: Update MFEXT documentation
  adm2/_yaml_to_md.py
  doc/Makefile
  doc/tutorial_layerapi2.ipynb
  layers/layer7_python2_devtools/0020_vim/Makefile.mk
Labels: Status: Review Needed

#338 build: remove python layer
  adm2/_metwork.spec
  adm2/templates/profile
  layers/layer9_default/.layerapi2_dependencies
  layers/layer9_python/.layerapi2_dependencies
  layers/layer9_python/.layerapi2_label
  layers/layer9_python/Makefile
  layers/layer9_python/layer_custom.md
  wrappers/Makefile
  wrappers/flake82.sh
  wrappers/flake83.sh
  wrappers/nosetests2.sh
  wrappers/nosetests3.sh
  wrappers/pylint2.sh
  wrappers/pylint3.sh
Labels: Merge Now, Status: Review Needed

#340 fix: obsoletes removed python layer
  adm2/_metwork.spec
Labels: Merge Now, Status: Review Needed

#341 build: obsoletes recently deleted python3 layer
  adm2/_metwork.spec
Labels: Merge Now, Status: Closed

#342 feat: add libev component
  layers/layer0_core/0015_libev/Makefile
  layers/layer0_core/0015_libev/Makefile.mk
  layers/layer0_core/0015_libev/sources
Labels: Status: Review Needed

#343 docs: fix invalid generated images link url
  doc/_images/logo-metwork.png
  doc/_images/metwork.ico
  doc/conf.py
Labels: Status: Review Needed

#344 build: add runtime dependencies for use of module tkinter in python2/3
  adm2/_metwork.spec
Labels: Status: Review Needed

#345 feat: add tkinter support thanks to a buildimage change
  CHANGELOG.md
Labels: Merge Now

#346 feat: add python tkinter support thanks to a change to the buildimage
  CHANGELOG.md
Labels: Merge Now, Status: Review Needed

#347 build: add tkinter test
  integration_tests/0004_test_import_python2/import_python2.py
  integration_tests/0004_test_import_python3/import_python3.py
Labels: Merge Now, Status: Review Needed, backport-to-0.5, backport-to-0.6

#350 build: add tcl/tk dependencies for scientific_core
  adm2/_metwork.spec
Labels: Merge Now, Status: Review Needed, backport-to-0.5, backport-to-0.6

#353 build: add tcl/tk requirements
  adm2/_metwork.spec
Labels: Merge Now

#354 build: add tcl/tk requirements
  adm2/_metwork.spec
Labels: Merge Now, Status: Review Needed

#355 build: fix tkinter import for python2
  integration_tests/0004_test_import_python2/import_python2.py
Labels: Merge Now, Status: Review Needed, backport-to-0.5, backport-to-0.6

#358 build: Add '.init' utility in generated 'layer_root'  documentation
  adm2/_doc_layer.sh
Labels: Status: Review Needed

#359 build: fix tcl/tk requirements
  adm2/_metwork.spec
Labels: Merge Now, Status: Review Needed

#360 build: fix gitignore
  .gitignore
Labels: Merge Now, Status: Review Needed

#361 Aliasesfix
  adm2/templates/bash_profile
  adm2/templates/interactive_profile
  layers/layer7_python2_devtools/.layerapi2_interactive_profile
  layers/layer7_python2_devtools/.layerapi2_interactive_unprofile
  layers/layer7_python2_devtools/0000_adm/Makefile
  layers/layer7_python2_devtools/0000_adm/Makefile.mk
  layers/layer7_python2_devtools/0000_adm/_vim
  layers/layer7_python2_devtools/0000_adm/_vimdiff
  layers/layer7_python3_devtools/.layerapi2_interactive_profile
  layers/layer7_python3_devtools/.layerapi2_interactive_unprofile
  layers/layer7_python3_devtools/0000_adm/Makefile
  layers/layer7_python3_devtools/0000_adm/Makefile.mk
  layers/layer7_python3_devtools/0000_adm/_vim
  layers/layer7_python3_devtools/0000_adm/_vimdiff
  wrappers/Makefile
  wrappers/vim_wrapper.sh
  wrappers/vimdiff_wrapper.sh
Labels: Merge Now, Status: Review Needed

#362 fix: close mflog issue11
  layers/layer2_python2/0500_extra_python_packages/requirements2.txt
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Merge Now, Status: Review Needed, backport-to-0.6, backport-to-0.7

#365 fix: close mflog issue11
  layers/layer2_python2/0500_extra_python_packages/requirements2.txt
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Merge Now

#366 build: update jsonlog2elasticsearch
  layers/layer8_monitoring/0500_extra_packages/requirements3.txt
Labels: Merge Now, Status: Review Needed, backport-to-0.7

#369 Fix vim wrapper with git editor
  adm2/templates/mfxxx_wrapper
  wrappers/Makefile
  wrappers/_vim_wrapper.sh
  wrappers/_vimdiff_wrapper.sh
  wrappers/vim_wrapper.sh
  wrappers/vimdiff_wrapper.sh
Labels: Status: Review Needed, backport-to-0.7
