Repository metwork-framework/mfext, pull requests merged in 2019-10, with the labels that each got.

#506 build: fix components list
  .metwork-framework/components.md
Labels: Merge Now, Status: Review Needed

#508 feat: update layerapi2
  .metwork-framework/components.md
  layers/layer0_core/0070_layerapi2/Makefile.mk
  layers/layer0_core/0070_layerapi2/sources
Labels: Merge Now, Status: Review Needed

#507 Update README.md
  .metwork-framework/README.md
Labels: Status: Review Needed

#510 build: obsoletes mfcom layers
  adm/_metwork.spec
Labels: Merge Now, Status: Review Needed

#511 build: fix rpm packaging (conflict with /etc/security/limits.d/50-met…
  adm/_metwork.spec
Labels: Merge Now, Status: Review Needed

#512 build: disable trace in cairo build (to fix python issue with matplot…
  layers/layer1_scientific_core/0025_cairo/Makefile.mk
Labels: Status: Review Needed

#513 Misc changes
  adm/metwork_debug
  adm/templates/interactive_profile
  layers/layer9_misc/0000_adm/_install_plugin_virtualenv
  layers/layer9_misc/0000_adm/_plugins.postinstall
  layers/layer9_misc/0000_adm/bootstrap_plugin.py
  layers/layer9_misc/0000_adm/plugin.mk
  layers/layer9_misc/0000_adm/plugin_wrapper
Labels: Status: Review Needed

#516 feat: infinite circus max_retry
  adm/templates/circus.ini
Labels: Status: Review Needed

#518 build: remove update available message
  layers/layer8_nodejs/.layerapi2_extra_env
Labels: Status: Review Needed, backport-to-0.8

#521 fix: don't write empty requirements{2,3}.txt file in case of errors
  layers/layer9_misc/0000_adm/plugin.mk
Labels: Status: Review Needed

#523 feat: add wrk tool to devtools layer
  layers/layer7_devtools/0060_wrk/Makefile
  layers/layer7_devtools/0060_wrk/Makefile.mk
  layers/layer7_devtools/0060_wrk/sources
Labels: Status: Review Needed

#524 feat: add wrk tool to devtools layer
  .metwork-framework/components.md
Labels: Status: Review Needed

#525 build: fix components.md
  .metwork-framework/components.md
Labels: Status: Review Needed

#527 feat: add some layerapi2 functions in mfutil
  layers/layer9_python3_misc/0100_mfutil/Makefile.mk
  layers/layer9_python3_misc/0100_mfutil/mfutil/glib2.py
  layers/layer9_python3_misc/0100_mfutil/mfutil/layerapi2.py
  layers/layer9_python3_misc/0100_mfutil/tests/test_layerapi2.py
Labels: Status: Review Needed

#526 fix: fix dead link to plugins guide
  layers/layer9_misc/0000_adm/bootstrap_plugin.py
Labels: Merge Now, Status: Review Needed

#529 build: update circus version
  layers/layer2_python3_circus/0500_circus/requirements3.txt
Labels: Merge Now, Status: Review Needed

#530 fix: external_plugins/ directory for mfbase
  adm/templates/mfxxx.start
Labels: Merge Now, Status: Review Needed

#533 build: fix backport 0.8
  adm/templates/mfxxx.start
Labels: Merge Now, Status: Review Needed

#532 fix: fix metwork services start for systems where /sys is readonly
  layers/layer9_misc/0000_adm/metwork
Labels: Status: Review Needed

#537 fix: fix systemd service
  layers/layer9_misc/0000_adm/metwork.service
Labels: Merge Now, Status: Review Needed, backport-to-0.9

#539 build: fix typo
  .drone.yml
Labels: Merge Now

#543 feat: add a banner about configured mfadmin module
  adm/templates/interactive_profile
  adm/templates/mfxxx.start
  layers/layer8_monitoring/.layerapi2_extra_env
Labels: Merge Now, Status: Review Needed, backport-to-0.9

#545 feat: better interactive/GUI processes detection
  adm/templates/interactive_profile
  adm/templates/mfxxx.start
Labels: Merge Now, Status: Review Needed, backport-to-0.9

#540 feat: systemd service improvments
  adm/templates/bash_profile
  adm/templates/mfxxx_wrapper
  layers/layer0_core/0045_mfutil_c/Makefile.mk
  layers/layer0_core/0045_mfutil_c/sources
  layers/layer9_misc/0000_adm/metwork
  layers/layer9_misc/0000_adm/metwork.service
Labels: Merge Now, Status: Review Needed, backport-to-0.9

#550 feat: add a clear warning...
  layers/layer9_python3_misc/0100_mfutil/mfutil/cli_tools/plugins_develop.py
  layers/layer9_python3_misc/0100_mfutil/mfutil/cli_tools/plugins_info.py
  layers/layer9_python3_misc/0100_mfutil/mfutil/cli_tools/plugins_install.py
Labels: Merge Now, Status: Review Needed, backport-to-0.9

#552 build: fix build
  .metwork-framework/components.md
Labels: Merge Now, Status: Review Needed

#558 build: fix warning in plugin_env
  adm/templates/interactive_profile
Labels: Merge Now, Status: Review Needed, backport-to-0.9

#561 fix: mfserv_wrapper now loads custom metwork profiles
  adm/templates/_mfxxx_wrapper
Labels: Merge Now, Status: Review Needed, backport-to-0.9

#557 Backport536
  .metwork-framework/components.md
  adm/templates/_mfxxx_wrapper
  adm/templates/bash_profile
  adm/templates/mfxxx_wrapper
  layers/layer0_core/0045_mfutil_c/Makefile.mk
  layers/layer0_core/0045_mfutil_c/sources
  layers/layer9_misc/0000_adm/metwork
  layers/layer9_misc/0000_adm/metwork.service
Labels: Merge Now, Status: Review Needed
