Repository metwork-framework/mfext, pull requests merged in 2020-09, with the labels that each got.

#887 build: fix rpm download url
  layers/layer1_rpm/0140_rpm/sources
Labels: Status: Merge Now, Status: Review Needed

#888 build: update jinja2_from_json_extension
  .metwork-framework/components.md
  layers/layer7_python3_devtools/0500_extra_python_packages/requirements3.txt
Labels: Status: Merge Now, Status: Review Needed

#893 build: update internal packages to fix urls in components.md (issue #821)
  .metwork-framework/components.md
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
  layers/layer2_python3_circus/0500_circus/requirements3.txt
Labels: Status: Review Needed

#899 feat: drop sphinx libraries (replaced by mkdocs)
  .metwork-framework/components.md
  Makefile
  adm/Makefile
  adm/_yaml_to_md.py
  adm/main_root.mk
  adm/sphinx_wrapper
  layers/layer7_devtools/0000_adm/Makefile.mk
  layers/layer7_devtools/0000_adm/sphinx_wrapper
  layers/layer7_python3_devtools/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer7_python3_devtools/0500_extra_python_packages/requirements3.txt
Labels: Status: Merge Now, Status: Review Needed

#912 feat: load the python3_scientific_core layer by default (if installed)
  layers/layer9_default/.layerapi2_dependencies
Labels: Status: Review Needed, backport-to-1.0
