Repository metwork-framework/mfext, pull requests merged in 2020-07, with the labels that each got.

#846 Tcltk without xft
  integration_tests/0004_test_import_python3/.layerapi2_dependencies
  layers/layer0_tcltk/.system_dependencies
  layers/layer0_tcltk/0020_tk/Makefile.mk
  layers/layer1_scientific_core/.system_dependencies
Labels: Merge Now, backport-to-1.0

#845 feat: manage git requirements without "-e"
  layers/layer1_python3_core/0000_adm/freeze_requirements
  layers/layer1_python3_core/0000_adm/install_requirements
Labels: backport-to-1.0

#859 feat: better prompt with virtualenv and better pip management
  adm/Makefile
  adm/pip_wrapper
  adm/templates/interactive_profile
Labels: backport-to-1.0

#862 build: acquisition update
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: backport-to-1.0

#867 build: reduce verbosity of lazy_import
  config/mflog_override.conf
Labels: Merge Now, backport-to-1.0

#871 build: doc about boostrapping
  adm/bootstrap_plugin.py
Labels: Merge Now

#872 Release 1.0 backport
  CHANGELOG.md
  adm/Makefile
  adm/bootstrap_plugin.py
  adm/pip_wrapper
  adm/templates/interactive_profile
  config/mflog_override.conf
  docs/100-installation_guide.md
  docs/300-configuration_guide.md
  docs/850-reference/_plugin_config_ini.md
  docs/Makefile
  docs/_plugin_ref_dev_commands.md
  docs/_plugin_ref_interesting_files.md
  docs/_plugin_ref_management_commands.md
  layers/Makefile.standard
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
  mkdocs.yml
Labels: Merge Now

#873 build: mfplugin update
  .metwork-framework/README.md
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Status: Review Needed, backport-to-1.0
