Repository metwork-framework/mfext, pull requests merged in 2020-02, with the labels that each got.

#696 build: remove a deprecated usage of mfutil
  adm/bootstrap_plugin.py
Labels: Merge Now, Status: Review Needed

#695 feat: better interactive profile for mfext
  adm/templates/interactive_profile
Labels: Status: Review Needed

#698 build: metwork-mfext-layer-python2_misc should be obsoleted
  adm/_metwork.spec
Labels: Merge Now, Status: Review Needed

#699 Experimental
  .metwork-framework/components.md
  layers/Makefile
  layers/layer0_core/0070_layerapi2/Makefile.mk
  layers/layer0_core/0070_layerapi2/sources
  layers/layer0_core/0080_log_proxy/Makefile.mk
  layers/layer0_core/0080_log_proxy/sources
  layers/layer1_scientific_core/0020_proj/Makefile.mk
  layers/layer1_scientific_core/0021_geos/Makefile.mk
  layers/layer1_scientific_core/0023_gdal/Makefile.mk
  layers/layer_wrapper.mk
  layers/python_layer_scl.mk
Labels: Merge Now, Status: Review Needed

#700 build: fix deploycron repository
  layers/layer2_python2/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer2_python2/0500_extra_python_packages/requirements2.txt
  layers/layer2_python3/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Merge Now, Status: Review Needed

#701 feat: update telegraf component
  layers/layer8_monitoring/0300_telegraf/Makefile.mk
  layers/layer8_monitoring/0300_telegraf/sources
Labels: Status: Review Needed

#706 build: update mfutil
  .metwork-framework/components.md
  layers/layer2_python2/0500_extra_python_packages/requirements2.txt
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Merge Now, Status: Review Needed

#707 build: update components list
  .metwork-framework/components.md
Labels: Merge Now, Status: Review Needed

#702 feat: use LOGPROXY_LOG_DIRECTORY env variable for log paths
  adm/templates/circus.ini
  adm/templates/crontab
  adm/templates/profile
Labels: Merge Now, Status: Review Needed

#704 feat: introduce automatic cleaning of tmp directory
  adm/templates/config.ini
  adm/templates/crontab
Labels: Merge Now, Status: Review Needed

#710 build: mfutil update
  layers/layer2_python2/0500_extra_python_packages/requirements2.txt
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Merge Now, Status: Review Needed

#708 Mfsysmon issue82
  .metwork-framework/components.md
  adm/telegraf_collector_metwork_module.py
  adm/templates/telegraf.conf
  layers/layer8_monitoring/0500_extra_packages/requirements-to-freeze.txt
  layers/layer8_monitoring/0500_extra_packages/requirements3.txt
Labels: Status: Review Needed

#709 feat: remove upload system account by default
  adm/_metwork.spec
Labels: Status: Review Needed

#712 fix: custom sysctl.conf was not applied during startup
  adm/Makefile
  adm/metwork
Labels: Status: Review Needed, backport-to-0.9

#714 feat: increase sysctl net.ipv4.tcp_max_syn_backlog
  config/sysctl_metwork.conf
Labels: Status: Review Needed

#715 fix: custom sysctl.conf was not applied during startup
  layers/layer9_misc/0000_adm/Makefile.mk
  layers/layer9_misc/0000_adm/metwork
Labels: Merge Now, Status: Review Needed

#718 Mfsysmon issue82 part2
  .metwork-framework/components.md
  adm/Makefile
  adm/send_stopped_state.py
  adm/telegraf_collector_metwork_module.py
  adm/templates/mfxxx.stop
  layers/layer2_python2/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer2_python2/0500_extra_python_packages/requirements2.txt
  layers/layer2_python3/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Status: Review Needed

#719 build: fix build
  integration_tests/0004_test_import_python2/import_python2.py
  integration_tests/0004_test_import_python3/import_python3.py
Labels: Merge Now, Status: Review Needed

#721 feat: update log_proxy to get dot control files
  .metwork-framework/components.md
  layers/layer0_core/0080_log_proxy/Makefile.mk
  layers/layer0_core/0080_log_proxy/sources
Labels: Status: Review Needed

#724 feat: add possibility to exclude files when releasing a plugin and up…
  .metwork-framework/components.md
  adm/plugin.mk
  layers/layer2_python2/0500_extra_python_packages/requirements2.txt
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Status: Review Needed

#725 build: some work about metwork-framework/mfsysmon#82
  adm/Makefile
  adm/_send_state.py
  adm/telegraf_collector_metwork_module.py
  adm/templates/mfxxx.start
  adm/templates/mfxxx.stop
Labels: Status: Review Needed

#726 build: little detail
  adm/telegraf_collector_metwork_module.py
Labels: Merge Now, Status: Review Needed

#727 build: update components.md
  .metwork-framework/components.md
Labels: Merge Now, Status: Review Needed

#731 build: add pathlib, missing dependency of gitignore-parser in python2
  .metwork-framework/components.md
  layers/layer2_python2/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer2_python2/0500_extra_python_packages/requirements2.txt
Labels: Status: Review Needed

#733 feat: do not build the layer if file .bypass_build_if_missing contain…
  layers/layer.mk
Labels: Status: Review Needed

#734 Misc3
  adm/templates/interactive_profile
  layers/layer2_python2/0500_extra_python_packages/requirements2.txt
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Merge Now, Status: Review Needed

#736 Remove python2
  .metwork-framework/components.md
  adm/_metwork.spec
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
  layers/layer2_python3_circus/0500_circus/requirements3.txt
Labels: Status: Review Needed

#737 build: update components.md
  .metwork-framework/components.md
Labels: Status: Review Needed
