Repository metwork-framework/mfext, pull requests merged in 2020-01, with the labels that each got.

#621 fix: fix plugin_env behaviour in some corner cases
  adm/plugin_wrapper
  adm/templates/interactive_profile
Labels: Merge Now, Status: Review Needed, backport-to-0.9

#623 build: better plugin_env fix
  adm/templates/interactive_profile
Labels: Merge Now, Status: Review Needed, backport-to-0.9

#625 [WIP] build: template changes for metwork-framework/resources#47
  .metwork-framework/components.md
  adm/Makefile
  adm/bash_utils.sh
  adm/config_subdir.mk
  adm/plugins_common.py
  adm/templates/circus.ini
  adm/templates/config.ini
  adm/templates/crontab
  adm/templates/logrotate.conf
  adm/templates/mfxxx.start
  adm/templates/mfxxx.status
  adm/templates/profile
  adm/templates/redis_plugin_xxx.conf
  layers/layer0_core/0080_log_proxy/Makefile.mk
  layers/layer0_core/0080_log_proxy/sources
Labels: Merge Now, Status: Review Needed

#628 feat: reintroduce MFCOM_HOME for plugins migration
  adm/templates/profile
Labels: Status: Review Needed

#629 feat: add mkdocs components
  .gitignore
  .metwork-framework/components.md
  layers/layer7_python2_devtools/0500_extra_python_packages/requirements2.txt
  layers/layer7_python3_devtools/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer7_python3_devtools/0500_extra_python_packages/requirements3.txt
Labels: Merge Now, Status: Review Needed

#631 build: first mkdocs doc
  .gitignore
  Makefile
  docs/010-whatis.md
  docs/020-quickstart.md
  docs/030-concepts.md
  docs/200-layerapi2.md
  docs/850-components.md
Labels: Merge Now, Status: Review Needed

#632 feat: update cronwrapper
  adm/templates/cronwrap.sh
  layers/layer2_python3/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Merge Now

#633 build: fix crontabs
  adm/_make_crontab.sh
  adm/templates/crontab
Labels: Merge Now, Status: Review Needed

#635 fix: remove some old aliases for vim in python2_devtools
  layers/layer7_python2_devtools/.layerapi2_interactive_profile
  layers/layer7_python2_devtools/.layerapi2_interactive_unprofile
Labels: Merge Now, Status: Review Needed, backport-to-0.9

#637 build: doc update
  .metwork-framework/components.md
  adm/_yaml_to_md.py
  adm/plugin_wrapper
  docs/030-concepts.md
  docs/850-components.md
Labels: Merge Now, Status: Review Needed

#639 build: doc improvements
  docs/030-concepts.md
  docs/750-utilities.md
  layers/layer1_python3_core/0000_adm/unsafe_pip
  layers/layer7_devtools/0000_adm/noutf8.sh
Labels: Merge Now, Status: Review Needed

#640 build: move docs makefile target in common makefile
  Makefile
  adm/main_root.mk
Labels: Merge Now, Status: Review Needed

#642 build: remove old doc directory
  .gitignore
  doc/Makefile
  doc/Makefile.mk
  doc/_images/logo-metwork.png
  doc/_images/metwork.ico
  doc/_static/css/override_theme.css
  doc/_static/empty
  doc/_templates/breadcrumbs.html
  doc/_templates/layout.html
  doc/changelogs.tmpl
  doc/conf.py
  doc/index.rst
  doc/layer_root_custom.md
  doc/layerapi2.md
  doc/layers.rst
  doc/tutorial_layerapi2.ipynb
Labels: Merge Now

#644 build: first part about #638
  adm/Makefile
  adm/jsonsyslog2es_metwork_addon.py
  adm/telegraf_collector_metwork_module.py
  adm/templates/circus.ini
Labels: Status: Review Needed

#645 build: part2 of issue638
  layers/layer9_python3_misc/0400_jsonlog2elasticsearch_metwork_addon/Makefile
  layers/layer9_python3_misc/0400_jsonlog2elasticsearch_metwork_addon/Makefile.mk
  layers/layer9_python3_misc/0400_jsonlog2elasticsearch_metwork_addon/jsonlog2elasticsearch_metwork_addon/__init__.py
  layers/layer9_python3_misc/0400_jsonlog2elasticsearch_metwork_addon/setup.py
Labels: Merge Now, Status: Review Needed

#646 feat: add pdoc3 python3 component
  .metwork-framework/components.md
  layers/layer7_python3_devtools/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer7_python3_devtools/0500_extra_python_packages/requirements3.txt
Labels: Merge Now, Status: Review Needed

#647 build: ignore a warning in flake8
  layers/layer7_devtools/0000_adm/flake82.sh
  layers/layer7_devtools/0000_adm/flake83.sh
Labels: Status: Review Needed

#648 feat: update openjdk from 11.0.2 to 11.0.5, with download from AdoptO…
  layers/layer8_java/0500_openjdk/Makefile.mk
  layers/layer8_java/0500_openjdk/sources
Labels: Status: Review Needed

#650 feat: new opinionated_configparser and corresponding changes
  .metwork-framework/components.md
  adm/Makefile
  adm/_ini_to_env.py
  adm/_prepare_config.py
  adm/config.py
  adm/templates/config_profile
  adm/templates/profile
  layers/layer2_python3/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Merge Now, Status: Review Needed

#652 Update centos8
  .metwork-framework/components.md
  adm/Makefile
  adm/_ini_to_env.py
  adm/_prepare_config.py
  adm/config.py
  adm/templates/config_profile
  adm/templates/profile
  layers/layer2_python3/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Status: Review Needed

#653 build: update components.md
  .metwork-framework/components.md
Labels: Status: Review Needed

#655 Experimental
  .gitignore
  .metwork-framework/components.md
  layers/Makefile
  layers/layer0_core/0005_pcre/Makefile.mk
  layers/layer0_core/0005_pcre/sources
  layers/layer0_core/0020_sqlite/Makefile.mk
  layers/layer0_core/0020_sqlite/sources
  layers/layer0_core/0027_cares/Makefile.mk
  layers/layer0_core/0027_cares/sources
  layers/layer0_core/0060_libxslt/Makefile.mk
  layers/layer0_core/0060_libxslt/sources
  layers/layer1_scientific_core/0005_openjpeg/Makefile.mk
  layers/layer1_scientific_core/0005_openjpeg/sources
  layers/layer1_scientific_core/0008_postgresql/Makefile.mk
  layers/layer1_scientific_core/0008_postgresql/sources
  layers/layer1_scientific_core/0011_hdf5/Makefile.mk
  layers/layer1_scientific_core/0011_hdf5/sources
  layers/layer1_scientific_core/0020_proj/Makefile
  layers/layer1_scientific_core/0020_proj/Makefile.mk
  layers/layer1_scientific_core/0020_proj/PJ_skmerc.c
  layers/layer1_scientific_core/0020_proj/accept_use_of_deprecated_proj_api_h.patch
  layers/layer1_scientific_core/0020_proj/patches
  layers/layer1_scientific_core/0020_proj/proj4-skewmercator.patch
  layers/layer1_scientific_core/0020_proj/sources
  layers/layer1_scientific_core/0020_proj4/Makefile.mk
  layers/layer1_scientific_core/0020_proj4/sources
  layers/layer1_scientific_core/0021_geos/Makefile.mk
  layers/layer1_scientific_core/0021_geos/sources
  layers/layer1_scientific_core/0022_libspatialite/Makefile.mk
  layers/layer1_scientific_core/0022_libspatialite/sources
  layers/layer1_scientific_core/0023_gdal/Makefile.mk
  layers/layer1_scientific_core/0023_gdal/sources
  layers/layer1_scientific_core/0024_pixman/Makefile
  layers/layer1_scientific_core/0024_pixman/Makefile.mk
  layers/layer1_scientific_core/0024_pixman/sources
  layers/layer1_scientific_core/0025_cairo/Makefile.mk
  layers/layer1_scientific_core/0025_cairo/sources
  layers/layer1_scientific_core/0070_postgis/Makefile.mk
  layers/layer1_scientific_core/0070_postgis/sources
  layers/layer7_devtools/0030_ack/Makefile.mk
  layers/layer7_devtools/0030_ack/sources
  layers/layer7_devtools/0030_the_silver_searcher/Makefile
  layers/layer7_devtools/0030_the_silver_searcher/Makefile.mk
  layers/layer7_devtools/0030_the_silver_searcher/no_lzma.patch
  layers/layer7_devtools/0030_the_silver_searcher/patches
  layers/layer7_devtools/0030_the_silver_searcher/sources
  layers/layer8_java/0500_openjdk/Makefile.mk
  layers/layer8_java/0500_openjdk/sources
  layers/layer8_nodejs/0500_nodejs/Makefile.mk
  layers/layer8_nodejs/0500_nodejs/sources
  layers/python_layer_scl.mk
Labels: Merge Now, Status: Review Needed

#654 feat: set default mfsysmon admin/hostname config to localhost
  adm/templates/config.ini
Labels: Status: Review Needed

#657 build: fix wrong integration tests
  integration_tests/0004_test_import_python2/import_python2.py
  integration_tests/0004_test_import_python3/import_python3.py
Labels: Merge Now

#659 build: remove jsonlog2elasticsearch
  .metwork-framework/components.md
  layers/layer8_monitoring/0500_extra_packages/requirements-to-freeze.txt
  layers/layer8_monitoring/0500_extra_packages/requirements3.txt
Labels: Status: Review Needed

#658 Miscchanges
  adm/Makefile
  adm/_ini_to_env.py
  adm/circus_hooks.py
  adm/conf_monitor.py
  adm/ini_to_env.py
  adm/mflog_addon.py
  adm/templates/circus.ini
  adm/templates/profile
  docs/750-utilities.md
Labels: Status: Review Needed

#660 build: mfsysmon build fix
  adm/_ini_to_env.py
  adm/ini_to_env.py
Labels: Merge Now, Status: Review Needed

#661 build: better doc
  .metwork-framework/README.md
  docs/300-configuration_guide.md
  docs/750-utilities.md
Labels: Merge Now

#666 fix: fix automatic restart
  adm/Makefile
  adm/_no_automatic_kill.sh
  adm/templates/crontab
  adm/templates/mfxxx.autorestart
  adm/templates/mfxxx.stop
Labels: Merge Now, Status: Review Needed, backport-to-0.9

#668 fix: fix automatic restart
  adm/Makefile
  adm/_no_automatic_kill.sh
  adm/templates/crontab
  adm/templates/mfxxx.autorestart
  adm/templates/mfxxx.stop
Labels: Merge Now, Status: Review Needed

#664 build: change nginx default error log
  layers/layer1_openresty/0100_openresty/Makefile.mk
Labels: Status: Review Needed

#665 feat: set TMPDIR automatically
  adm/plugin_wrapper
  adm/templates/profile
Labels: Status: Review Needed

#670 build: fix typo
  adm/templates/mfxxx.stop
Labels: Merge Now, Status: Review Needed

#672 fix: fix nasty warning in mfdata plugin_env when admin is set
  adm/templates/interactive_profile
Labels: Merge Now, Status: Review Needed, backport-to-0.9

#675 fix: fix nasty warning in mfdata plugin_env when admin is set
  adm/templates/interactive_profile
Labels: Merge Now, Status: Review Needed

#674 Miscchanges3
  .metwork-framework/README.md
  adm/components
Labels: Merge Now, Status: Review Needed

#676 feat: cronwrap load custom profiles like bashrc/profile
  adm/templates/cronwrap.sh
Labels: Merge Now, Status: Review Needed, backport-to-0.9

#678 build: drop of circus_hooks, mflog_addon and conf_monitor
  layers/layer9_python2_misc/0500_mflog_addon/Makefile
  layers/layer9_python2_misc/0500_mflog_addon/Makefile.mk
  layers/layer9_python2_misc/0500_mflog_addon/mflog_metwork_addon
  layers/layer9_python2_misc/0500_mflog_addon/setup.py
  layers/layer9_python3_misc/0300_circus_hooks/Makefile
  layers/layer9_python3_misc/0300_circus_hooks/Makefile.mk
  layers/layer9_python3_misc/0300_circus_hooks/circus_hooks/__init__.py
  layers/layer9_python3_misc/0300_circus_hooks/setup.py
  layers/layer9_python3_misc/0300_conf_monitor/Makefile
  layers/layer9_python3_misc/0300_conf_monitor/Makefile.mk
  layers/layer9_python3_misc/0300_conf_monitor/conf_monitor/__init__.py
  layers/layer9_python3_misc/0300_conf_monitor/setup.py
  layers/layer9_python3_misc/0500_mflog_addon/Makefile
  layers/layer9_python3_misc/0500_mflog_addon/Makefile.mk
  layers/layer9_python3_misc/0500_mflog_addon/mflog_metwork_addon/__init__.py
  layers/layer9_python3_misc/0500_mflog_addon/setup.py
Labels: Status: Review Needed

#669 feat: plugins checks
  adm/Makefile
  adm/_plugins.start
  adm/_plugins.status
  adm/_plugins.stop
  adm/circus.py
  adm/conf_monitor.py
  adm/plugins.start
  adm/plugins.status
  adm/plugins.stop
  adm/templates/mfxxx.start
  adm/templates/mfxxx.status
  adm/templates/mfxxx.stop
  layers/layer2_python3_circus/0500_circus/requirements3.txt
  layers/layer9_python3_misc/0100_mfutil/mfutil/cli.py
Labels: Merge Now, Status: Review Needed

#680 feat: cronwrap load custom profiles like bashrc/profile
  adm/templates/cronwrap.sh
Labels: Merge Now, Status: Review Needed

#679 build: update log_proxy
  .metwork-framework/components.md
  layers/layer0_core/0080_log_proxy/Makefile.mk
  layers/layer0_core/0080_log_proxy/sources
Labels: Merge Now, Status: Review Needed

#683 build: fix (SC2086)
  adm/templates/profile
Labels: Merge Now, Status: Review Needed

#681 build: preparing metwork-framework/resources#39
  adm/plugins_common.py
Labels: Status: Review Needed

#686 fix: fix pip usage inside plugin_env (and change cwd for plugin_home)
  adm/templates/interactive_profile
Labels: Status: Review Needed, backport-to-0.9

#689 feat: if core_size = -1, ulimit -c is not set
  adm/templates/config.ini
  adm/templates/profile
Labels: Status: Review Needed

#691 feat: build all mfext with devtoolset-8 (gcc-8)
  layers/Makefile
  layers/layer0_core/0070_layerapi2/Makefile.mk
  layers/layer0_core/0070_layerapi2/sources
  layers/layer0_core/0080_log_proxy/Makefile.mk
  layers/layer0_core/0080_log_proxy/sources
  layers/layer1_scientific_core/0020_proj/Makefile.mk
  layers/layer1_scientific_core/0021_geos/Makefile.mk
  layers/layer1_scientific_core/0023_gdal/Makefile.mk
  layers/layer_wrapper.mk
  layers/python_layer_scl.mk
Labels: Status: Review Needed

#692 Update components.md
  .metwork-framework/components.md
Labels: Status: Review Needed
