Repository metwork-framework/mfext, pull requests merged in 2020-03, with the labels that each got.

#738 build: part2 of metwork-framework/mfserv#269
  adm/_plugins.status
Labels: Status: Review Needed

#740 build: add bjoern (moved from mfserv)
  layers/layer2_python3/0550_bjoern/Makefile
  layers/layer2_python3/0550_bjoern/Makefile.mk
  layers/layer2_python3/0550_bjoern/sources
Labels: Status: Review Needed

#741 build: add bjoern (moved from mfserv)
  layers/layer2_python3/0550_bjoern/Makefile.mk
Labels: Status: Review Needed

#742 build: update components.md
  .metwork-framework/components.md
Labels: Status: Review Needed

#743 Remove python2
  adm/_metwork.spec
Labels: Status: Review Needed

#746 fix: fix issue 745 (problem with blank lines while editing crontab)
  adm/_make_crontab.sh
Labels: Status: Review Needed

#747 build: fix because of SC1117
  adm/_make_crontab.sh
Labels: Status: Review Needed

#750 feat: cronwrapper update
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Status: Review Needed

#749 feat: we can use *_CURRENT_PLUGIN_* variables in plugin crontabs
  adm/Makefile
  adm/_make_and_install_crontab.sh
  adm/_make_crontab.py
  adm/_make_crontab.sh
  adm/conf_monitor.py
Labels: Merge Now, Status: Review Needed

#751 feat: mflog update
  layers/layer2_python2/0500_extra_python_packages/requirements2.txt
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Merge Now

#752 build: automatic mflog configuration
  adm/templates/mflog_override.conf
  adm/templates/profile
Labels: Merge Now, Status: Review Needed

#753 Misc4
  adm/_make_crontab.py
  adm/templates/telegraf.conf
  layers/layer2_python2/0500_extra_python_packages/requirements2.txt
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Merge Now, Status: Review Needed

#757 feat: upgrade netcdf_c from 4.7.0 to 4.7.3
  layers/layer1_scientific_core/0012_netcdf_c/Makefile.mk
  layers/layer1_scientific_core/0012_netcdf_c/sources
Labels: Status: Review Needed

#758 build: upgrade psutil from 5.6.3 to 5.6.6 to fix security issue
  .metwork-framework/components.md
  layers/layer2_python2/0500_extra_python_packages/requirements2.txt
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Status: Review Needed

#759 build: fix components.md
  .metwork-framework/components.md
Labels: Merge Now, Status: Review Needed

#761 feat: add fontconfig and freetype (moved from mfextaddon_scientific)
  .metwork-framework/components.md
  layers/layer1_scientific_core/.system_dependencies
  layers/layer1_scientific_core/0030_freetype/Makefile
  layers/layer1_scientific_core/0030_freetype/Makefile.mk
  layers/layer1_scientific_core/0030_freetype/sources
  layers/layer1_scientific_core/0031_fontconfig/Makefile
  layers/layer1_scientific_core/0031_fontconfig/Makefile.mk
  layers/layer1_scientific_core/0031_fontconfig/sources
  layers/layer1_scientific_core/0032_cairo/Makefile
  layers/layer1_scientific_core/0032_cairo/Makefile.mk
  layers/layer1_scientific_core/0032_cairo/sources
Labels: Status: Review Needed

#763 feat: cronwrapper update to fix uid collisions when mfserv is launche…
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Status: Review Needed

#762 feat: update log_proxy to fix problem when a maximum file size if set…
  layers/layer0_core/0080_log_proxy/Makefile.mk
  layers/layer0_core/0080_log_proxy/sources
Labels: Status: Review Needed

#765 feat: upgrade netcdf_c from 4.7.0 to 4.7.3
  layers/layer1_scientific_core/0012_netcdf_c/Makefile.mk
  layers/layer1_scientific_core/0012_netcdf_c/sources
Labels: Merge Now

#766 build: update components.md
  .metwork-framework/components.md
Labels: Merge Now

#767 build: update components.md
  .metwork-framework/components.md
Labels: Merge Now

#769 fix: fix again a little warning
  layers/layer9_misc/0000_adm/after_stop_nginx
  layers/layer9_misc/0000_adm/before_start_nginx
Labels: Merge Now, Status: Review Needed

#770 build: fix build
  layers/layer9_misc/0000_adm/Makefile.mk
Labels: Merge Now, Status: Review Needed

#771 build: remove nginx warning in some corner cases
  adm/Makefile
  adm/after_stop_nginx
  adm/before_start_nginx
Labels: Status: Review Needed

#772 feat: update mfutil to get explicit error messages in some cases when…
  layers/layer2_python2/0500_extra_python_packages/requirements2.txt
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Status: Review Needed

#773 Plpythonu
  layers/layer1_scientific_core/0008_postgresql/.build_extra_dependencies
  layers/layer1_scientific_core/0008_postgresql/Makefile.mk
  layers/layer_wrapper.mk
Labels: Status: Review Needed

#774 fix: fix compatibility with old systemd versions
  adm/metwork.service
Labels: Status: Review Needed

#775 build: add possibility to extract files from a rpm
  layers/_uncompress_helper.sh
Labels: Status: Review Needed

#776 fix: mfxxx.status must return 1 when errors occur
  adm/templates/mfxxx.status
Labels: Merge Now, Status: Review Needed
