Repository metwork-framework/mfext, pull requests merged in 2020-10, with the labels that each got.

#917 feat: build postgresql with extension unaccent (for usage in mfbase)
  layers/layer1_scientific_core/0008_postgresql/Makefile.mk
Labels: Status: Review Needed, backport-to-0.9

#922 build: remove dev config
  adm/templates/config.ini
Labels: Status: Review Needed, backport-to-1.0

#924 fix: give up profile loading when a required layer is missing (with a…
  adm/templates/profile
Labels: Status: Review Needed, backport-to-1.0

#927 fix: don't prevent mfserv/nginx to bind <1024 ports with setcap
  adm/_metwork.spec
  adm/metwork
Labels: Status: Merge Now, Status: Review Needed, backport-to-0.9, backport-to-1.0

#930 build: just a change to force a CI event
  README.md
Labels: Status: Merge Now

#937 fix: don't block root usage in CI configurations
  adm/bash_utils.sh
Labels: backport-to-0.9, backport-to-1.0
