Repository metwork-framework/mfext, pull requests merged in 2020-05, with the labels that each got.

#789 feat: new plugin system
  .metwork-framework/components.md
  adm/Makefile
  adm/_circusctl
  adm/_install_or_update_configured_plugins.py
  adm/_make_crontab.py
  adm/_metwork.spec
  adm/_plugins.postinstall
  adm/_plugins.preuninstall
  adm/_plugins.start
  adm/_plugins.status
  adm/_plugins.stop
  adm/_prepare_plugin_config.py
  adm/_remove_plugin_config.py
  adm/bootstrap_plugin.py
  adm/conf_monitor.py
  adm/ini_to_env.py
  adm/plugin.mk
  adm/plugin_autorestart_excludes
  adm/plugin_autorestart_includes
  adm/plugin_wrapper
  adm/plugins_common.py
  adm/telegraf_collector_metwork_module.py
  adm/templates/circus.ini
  adm/templates/interactive_profile
  adm/templates/mfxxx.init
  adm/templates/mfxxx.start
  adm/templates/plugin.spec
  docs/200-layerapi2.md
  integration_tests/0004_test_import_python2/import_python2.py
  integration_tests/0004_test_import_python3/import_python3.py
  layers/layer1_python2_core/0000_adm/Makefile.mk
  layers/layer1_rpm/.layerapi2_dependencies
  layers/layer1_rpm/.layerapi2_label
  layers/layer1_rpm/.system_dependencies
  layers/layer1_rpm/0135_db/Makefile.mk
  layers/layer1_rpm/0135_db/sources
  layers/layer1_rpm/0140_rpm/Makefile.mk
  layers/layer1_rpm/0140_rpm/sources
  layers/layer1_rpm/Makefile
  layers/layer1_rpm/layer_custom.md
  layers/layer2_python2/0500_extra_python_packages/requirements2.txt
  layers/layer2_python3/0400_prereq_extra_python_packages/Makefile
  layers/layer2_python3/0400_prereq_extra_python_packages/Makefile.mk
  layers/layer2_python3/0400_prereq_extra_python_packages/requirements-to-freeze.txt
  layers/layer2_python3/0400_prereq_extra_python_packages/requirements3.txt
  layers/layer2_python3/0498_configupdater/Makefile
  layers/layer2_python3/0498_configupdater/Makefile.mk
  layers/layer2_python3/0498_configupdater/sources
  layers/layer2_python3/0499_prereq_extra_python_packages/Makefile
  layers/layer2_python3/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
  layers/layer2_python3_circus/0500_circus/requirements3.txt
  layers/layer7_python3_devtools/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer7_python3_devtools/0500_extra_python_packages/requirements3.txt
Labels: Merge Now, Status: Review Needed

#790 build: mfplugin update
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Merge Now, Status: Review Needed

#792 fix: fix systemctl startup with some circusctl versions
  layers/layer9_misc/0000_adm/metwork.service
Labels: Merge Now, Status: Review Needed

#791 build: use a timeout in systemctl start (just in case...)
  adm/metwork.service
Labels: Merge Now, Status: Review Needed

#783 feat: remove all references to MFCOM or mfcom, including backward com…
  .layerapi2_extraenv
  adm/_make_crontab.py
  adm/_make_nethard_config.py
  adm/_metwork.spec
  adm/_send_state.py
  adm/jsonsyslog2es_metwork_addon.py
  adm/templates/interactive_profile
  adm/templates/nethard_profile
  adm/templates/profile
  adm/templates/telegraf.conf
Labels: Status: Review Needed

#795 Update components.md
  .metwork-framework/components.md
Labels: Merge Now, Status: Review Needed

#796 Update components
  layers/layer0_core/0200_ctags/sources
Labels: Status: Review Needed

#797 feat: add paramiko (python implementation of SSHv2) and dependencies
  .metwork-framework/components.md
  layers/layer2_python3/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Status: Review Needed

#800 build: little fix with virtualenv
  adm/templates/interactive_profile
Labels: Status: Review Needed

#802 Issue801
  adm/templates/profile
  layers/layer9_python3_misc/0100_mfutil/mfutil/cli_tools/plugins_info.py
Labels: Merge Now, Status: Review Needed

#805 Misc changes
  .metwork-framework/components.md
  adm/kill_remaining_processes.py
  adm/plugin.mk
  adm/templates/mfxxx.stop
  adm/templates/profile
  layers/layer1_python3_core/0000_adm/install_requirements
  layers/layer2_python3/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
  layers/layer7_python3_devtools/0500_extra_python_packages/requirements3.txt
Labels: Status: Review Needed

#806 build: fix components.md
  .metwork-framework/components.md
Labels: Merge Now, Status: Review Needed

#807 build: update "internal" python components
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Status: Review Needed

#808 build: update mfplugin
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Merge Now, Status: Review Needed

#809 build: mfplugin update
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Merge Now

#810 feat: add python3 devtools components (pytest-xdist, pytest-mock, fre…
  .metwork-framework/components.md
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
  layers/layer7_python3_devtools/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer7_python3_devtools/0500_extra_python_packages/requirements3.txt
Labels: Status: Review Needed

#812 build: mfplugin update
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Merge Now, backport-to-1.0
