Repository metwork-framework/mfext, pull requests merged in 2020-12, with the labels that each got.

#1010 fix: add missing postgresql support in gdal
  integration_tests/0002_check_gdal_supports/.layerapi2_dependencies
  integration_tests/0002_check_gdal_supports/test_gdal_supports.sh
  layers/layer1_scientific_core/0023_gdal/Makefile.mk
Labels: Status: Review Needed, backport-to-1.0

#1015 fix: fix template crontab
  adm/templates/crontab
Labels: Status: Merge Now, Status: Review Needed, backport-to-1.0

#1020 build: fix for centos6 EOL
  .drone.yml
Labels: Status: Review Needed, backport-to-0.9

#1021 build: update .drone.yml
  .drone.yml
Labels: Status: Merge Now, Status: Review Needed, backport-to-0.9

#1011 feat: upgrade pip from 18.1 to 20.2.4 (18.1 is too old to install som…
  .metwork-framework/components.md
  layers/layer1_python3_core/0000_adm/download_compile_requirements
  layers/layer1_python3_core/0046_pip/Makefile.mk
  layers/layer1_python3_core/0046_pip/sources
  layers/layer2_python3/0500_extra_python_packages/allow_binary_packages
Labels: Status: Review Needed

#1024 build: fix image used for integration tests after centos6 EOL
  .drone.yml
Labels: Status: Review Needed

#1025 feat: add xz (which allows to add lzma support in python, gdal, ...)
  .metwork-framework/components.md
  integration_tests/0004_test_import_python3/import_python3.py
  layers/layer0_core/0003_xz/Makefile
  layers/layer0_core/0003_xz/Makefile.mk
  layers/layer0_core/0003_xz/patches
  layers/layer0_core/0003_xz/sources
  layers/layer0_core/0003_xz/xz5.1.2alpha.patch
  layers/layer0_core/0050_libxml/Makefile.mk
Labels: Status: Review Needed

#1027 build: move Markdown and tqdm from python3_devtools to python3 (they …
  layers/layer2_python3/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
  layers/layer7_python3_devtools/0500_extra_python_packages/requirements3.txt
Labels: Status: Review Needed

#1045 build: update .drone.yml (add triggers centos7 and centos8)
  .drone.yml
Labels: Status: Review Needed
