Repository metwork-framework/mfext, pull requests merged in 2020-11, with the labels that each got.

#944 fix: fix an issue with inject_file command in mfdata
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: backport-to-1.0

#950 fix: fix an issue in mfdata acquisition about default values in get_config_value()
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Status: Revision Needed, backport-to-1.0

#960 feat: add pytest-html and missing dependencies on other packages
  layers/layer7_python3_devtools/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer7_python3_devtools/0500_extra_python_packages/requirements3.txt
Labels: Status: Review Needed

#961 feat: add nose-html-reporting
  .metwork-framework/components.md
  layers/layer7_python3_devtools/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer7_python3_devtools/0500_extra_python_packages/requirements3.txt
Labels: Status: Review Needed

#963 build: update internal packages, add missing dependencies and use pypi version of mflog
  .metwork-framework/components.md
  layers/layer2_python3/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
  layers/layer2_python3_circus/0500_circus/requirements3.txt
  layers/layer8_monitoring/0500_extra_packages/requirements3.txt
Labels: Status: Review Needed, Status: Revision Needed

#965 build: fix wrong commit number for circus
  layers/layer2_python3_circus/0500_circus/requirements3.txt
Labels: Status: Merge Now

#966 fix: fix a cache issue with python custom functions with same name
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Status: Review Needed, backport-to-1.0

#970 build: move wrapt and zipp from python3_devtools to python3 (they are also used in addon scientific)
  .metwork-framework/components.md
  layers/layer2_python3/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
  layers/layer7_python3_devtools/0500_extra_python_packages/requirements3.txt
Labels: Status: Review Needed

#971 build: fix components.md
  .metwork-framework/components.md
Labels: Status: Merge Now

#975 fix: update opinionated_configparser
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Status: Review Needed, backport-to-1.0

#977 fix: fix error message in nginx_error with < 1024 port binding
  adm/metwork
  layers/layer1_openresty/0500_mfutil_lua/Makefile.mk
  layers/layer1_openresty/0500_mfutil_lua/sources
Labels: Status: Review Needed, backport-to-0.9, backport-to-1.0

#985 build: fix mfutil_lua version
  .metwork-framework/components.md
Labels: Status: Merge Now, Status: Review Needed, backport-to-0.9, backport-to-1.0

#980 build: upgrade setuptools and setuptools_scm to fix install of some r…
  .metwork-framework/components.md
  layers/layer1_python3_core/0044_setuptools/Makefile.mk
  layers/layer1_python3_core/0044_setuptools/sources
  layers/layer2_python3/0400_prereq_extra_python_packages/requirements-to-freeze.txt
  layers/layer2_python3/0400_prereq_extra_python_packages/requirements3.txt
  layers/layer2_python3/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
  layers/layer7_python3_devtools/0500_extra_python_packages/requirements3.txt
Labels: Status: Merge Now, Status: Review Needed

#989 build: Allow mixing of source and binary installs
  layers/layer1_python3_core/0000_adm/download_compile_requirements
Labels: Status: Review Needed

#990 build: fix download_compile_requirements
  layers/layer1_python3_core/0000_adm/download_compile_requirements
Labels: Status: Review Needed, Status: Revision Needed

#991 fix: fix an interactive question in some cases during profile loading
  adm/templates/profile
Labels: Status: Review Needed, backport-to-1.0

#996 feat: move jinja2 extensions packages to python3 layer
  .metwork-framework/components.md
  layers/layer2_python3/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
  layers/layer7_python3_devtools/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer7_python3_devtools/0500_extra_python_packages/requirements3.txt
Labels: Status: Review Needed, backport-to-1.0

#999 fix: fix an issue with < 1024 port binding
  adm/templates/cronwrap.sh
Labels: Status: Review Needed, backport-to-0.9, backport-to-1.0

#1003 fix: fix missing deps in centos8
  layers/layer9_default/.system_dependencies
Labels: Status: Review Needed, backport-to-1.0
