Repository metwork-framework/mfext, pull requests merged in 2021-05, with the labels that each got.

#1120 build: update workflows (from common files)
  .github/workflows/build.sh
  .github/workflows/ci.yml
  .github/workflows/createrepo.sh
Labels: Status: Merge Now, Status: Review Needed

#1121 feat: bump urllib3 from 1.25.3 to 1.25.11 to fix a security vulnerabi…
  .metwork-framework/components.md
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Status: Review Needed, backport-to-1.0, backport-to-1.1

#1122 feat: go back to Jinja2 2.10.1 (Magics 4.2.0 on mfextaddon_scientific does not build with 2.11.3 and python 3.7)
  .metwork-framework/components.md
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Status: Review Needed

#1119 feat: update py from 1.8.1 to 1.10.0 to fix security alert (CVE-2020-…
  .metwork-framework/components.md
  layers/layer7_python3_devtools/0500_extra_python_packages/requirements3.txt
Labels: Status: Review Needed, backport-to-1.0, backport-to-1.1

#1127 build: update ci.yml (mageia repo metadata)
  .github/workflows/ci.yml
Labels: Status: Merge Now, Status: Review Needed

#1131 fix: fix vector usage in mfadmin module
  adm/templates/vector.toml
Labels: Status: Review Needed, backport-to-1.1

#1133 build: update CI from integration branch
  .github/workflows/build.sh
  .github/workflows/ci.yml
  .github/workflows/set_variables.sh
Labels: Status: Merge Now, Status: Review Needed

#1135 build: CI under github actions
  .drone.yml
  .github/workflows/bootstrap_ci.sh
  .github/workflows/build.sh
  .github/workflows/ci.yml
  .github/workflows/createrepo.sh
  .github/workflows/integration_tests.sh
  .github/workflows/set_variables.sh
Labels: Status: Merge Now

#1134 fix: fix MFEXT_VERSION env with released versions
  adm/templates/profile
Labels: Status: Merge Now, Status: Review Needed, backport-to-1.0, backport-to-1.1

#1140 fix: update vector component to fix some loki issues
  .metwork-framework/components.md
  layers/layer8_monitoring/0400_vector/Makefile.mk
  layers/layer8_monitoring/0400_vector/sources
Labels: Status: Review Needed, backport-to-1.1

#1141 fix: add a timeout in kill remaining processes
  adm/templates/mfxxx.stop
Labels: Status: Review Needed, backport-to-1.0, backport-to-1.1

#1145 feat: add jq and its dependency onig
  .metwork-framework/components.md
  layers/layer0_core/0209_onig/Makefile
  layers/layer0_core/0209_onig/Makefile.mk
  layers/layer0_core/0209_onig/sources
  layers/layer0_core/0210_jq/Makefile
  layers/layer0_core/0210_jq/Makefile.mk
  layers/layer0_core/0210_jq/sources
Labels: Status: Review Needed

#1146 build: fix jq and onig builds
  layers/layer0_core/0209_onig/Makefile.mk
  layers/layer0_core/0210_jq/Makefile.mk
Labels: Status: Merge Now

#1147 fix: delete .configuration_cache during make clean
  adm/plugin.mk
Labels: Status: Review Needed
