Repository metwork-framework/mfext, pull requests merged in 2021-12, with the labels that each got.

#1237 fix: fix acquisition module with python 3.9
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Status: Revision Needed, Status: Merge Now, backport-to-1.2

#1239 build: fix components.md
  .metwork-framework/components.md
Labels: Status: Review Needed, Status: Merge Now, backport-to-1.2

#1242 feat: add a new control file "override" to override metwork python pa…
  layers/layer1_python3_core/0000_adm/download_compile_requirements
  layers/layer1_python3_core/0000_adm/freeze_requirements
  layers/layer1_python3_core/0000_adm/install_requirements
Labels: Status: Review Needed, backport-to-1.1, backport-to-1.2
