Repository metwork-framework/mfext, pull requests merged in 2021-11, with the labels that each got.

#1220 fix: fix pip options usage
  layers/layer1_python3_core/0000_adm/freeze_requirements
Labels: Status: Merge Now, backport-to-1.1

#1222 build: fix advanced pip options usage (part2)
  layers/layer1_python3_core/0000_adm/install_requirements
Labels: Status: Merge Now, backport-to-1.1

#1224 build: fix lattest commit
  layers/layer1_python3_core/0000_adm/install_requirements
Labels: Status: Merge Now, backport-to-1.1

#1227 fix: fix regex which block the installation of httpx package
  layers/layer1_python3_core/0000_adm/freeze_requirements
Labels: Status: Review Needed, backport-to-1.1

#1231 build: remove changelog files with wrong name
  CHANGELOG.md-0.7
  CHANGELOG.md-0.8
  CHANGELOG.md-0.9
  CHANGELOG.md-1.0
  CHANGELOG.md-1.1
Labels: Status: Merge Now

#1232 feat: add libtiff to add tiff support in several scientific packages …
  .metwork-framework/components.md
  layers/layer1_scientific_core/0004_libtiff/Makefile
  layers/layer1_scientific_core/0004_libtiff/Makefile.mk
  layers/layer1_scientific_core/0004_libtiff/sources
Labels: Status: Review Needed, Status: Merge Now, backport-to-1.2

#1235 build: force build
  layers/layer1_scientific_core/0004_libtiff/Makefile.mk
Labels: Status: Review Needed, Status: Merge Now

#1234 build: fix download url for pcre
  layers/layer0_core/0005_pcre/sources
Labels: Status: Merge Now, backport-to-1.2
