Repository metwork-framework/mfext, pull requests merged in 2021-02, with the labels that each got.

#1059 fix: fix some various issues with stop/start of modules
  .metwork-framework/components.md
  adm/Makefile
  adm/_circus_schedule_start_watcher.py
  adm/_circus_schedule_start_watcher.sh
  adm/_circus_schedule_stop_watcher.py
  adm/_circus_schedule_stop_watcher.sh
  adm/_circus_wait.py
  adm/_circus_wait.sh
  adm/_circus_wait_watcher_started.py
  adm/_circus_wait_watcher_started.sh
  adm/_circus_wait_watcher_stopped.py
  adm/_circus_wait_watcher_stopped.sh
  adm/_plugins.stop
  adm/circus.py
  adm/repeat.sh
  adm/templates/mfxxx.start
  adm/templates/mfxxx.stop
  adm/wait_redis.py
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Status: Review Needed, backport-to-1.0

#1064 build: fix test
  adm/repeat.sh
Labels: Status: Merge Now, backport-to-1.0

#1066 build: update mfutil to fix a bug with mfprogress/timeout in centos6
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Status: Merge Now, backport-to-1.0

#1068 feat: add vector tool (for preparing loki)
  .metwork-framework/components.md
  adm/Makefile
  adm/before_start_vector
  adm/config_subdir.mk
  adm/templates/config.ini
  adm/templates/vector.toml
  layers/layer8_monitoring/0400_vector/Makefile
  layers/layer8_monitoring/0400_vector/Makefile.mk
  layers/layer8_monitoring/0400_vector/sources
Labels: Status: Review Needed

#1069 build: add vector (part 2) and remove jsonsyslog2es
  .metwork-framework/components.md
  adm/Makefile
  adm/jsonsyslog2es_metwork_addon.py
  adm/telegraf_collector_metwork_module.py
  adm/templates/circus.ini
  adm/templates/mfxxx.start
  adm/templates/mfxxx.status
  adm/templates/profile
  layers/layer8_monitoring/0500_extra_packages/requirements-to-freeze.txt
  layers/layer8_monitoring/0500_extra_packages/requirements3.txt
Labels: Status: Revision Needed

#1071 build: back to pip wheel with option --no-build-isolation (file build…
  layers/layer1_python3_core/0000_adm/download_compile_requirements
Labels: Status: Review Needed
