Repository metwork-framework/mfext, pull requests merged in 2021-03, with the labels that each got.

#1073 fix: remove old useless configuration key
  adm/templates/config.ini
Labels: Status: Review Needed, backport-to-1.0

#1075 feat: upgrade aiohttp from 3.6.3 to 3.7.4 to fix security vulnerability
  .metwork-framework/components.md
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Status: Review Needed

#1076 fix: prevent a circus crash in some corner cases
  layers/layer2_python3_circus/0500_circus/requirements3.txt
Labels: Status: Review Needed, backport-to-0.9, backport-to-1.0

#1079 build: fix access url to libspatialite
  layers/layer1_scientific_core/0022_libspatialite/sources
Labels: Status: Review Needed

#1080 build: fix python2 build
  .metwork-framework/components.md
  layers/layer2_python2/0499_prereq_extra_python_packages/requirements-to-freeze.txt
  layers/layer2_python2/0499_prereq_extra_python_packages/requirements2.txt
Labels: Status: Review Needed

#1081 feat: upgrade python3 from 3.7.3 to 3.7.10
  .metwork-framework/components.md
  layers/layer1_python3_core/0030_python3/Makefile.mk
  layers/layer1_python3_core/0030_python3/sources
Labels: Status: Review Needed

#1082 feat: upgrade setuptools from 42.0.2 to 54.1.2 with refactoring of la…
  .gitignore
  .metwork-framework/components.md
  layers/layer1_python3_core/0030_python3/Makefile.mk
  layers/layer1_python3_core/0032_wheel/Makefile
  layers/layer1_python3_core/0032_wheel/Makefile.mk
  layers/layer1_python3_core/0032_wheel/sources
  layers/layer1_python3_core/0033_upgrade_pip_setuptools/Makefile
  layers/layer1_python3_core/0033_upgrade_pip_setuptools/Makefile.mk
  layers/layer1_python3_core/0033_upgrade_pip_setuptools/requirements-to-freeze.txt
  layers/layer1_python3_core/0033_upgrade_pip_setuptools/requirements3.txt
  layers/layer1_python3_core/0041_six/Makefile.mk
  layers/layer1_python3_core/0041_six/sources
  layers/layer1_python3_core/0042_appdirs/Makefile.mk
  layers/layer1_python3_core/0042_appdirs/sources
  layers/layer1_python3_core/0043_packaging/Makefile.mk
  layers/layer1_python3_core/0043_packaging/sources
  layers/layer1_python3_core/0044_setuptools/Makefile.mk
  layers/layer1_python3_core/0044_setuptools/sources
  layers/layer1_python3_core/0045_pyparsing/Makefile
  layers/layer1_python3_core/0045_pyparsing/Makefile.mk
  layers/layer1_python3_core/0045_pyparsing/sources
  layers/layer1_python3_core/0046_pip/Makefile
  layers/layer1_python3_core/0046_pip/Makefile.mk
  layers/layer1_python3_core/0046_pip/sources
  layers/layer1_python3_core/0046_virtualenv/Makefile
  layers/layer1_python3_core/0046_virtualenv/Makefile.mk
  layers/layer1_python3_core/0046_virtualenv/sources
  layers/layer1_python3_core/0050_wheel/Makefile
  layers/layer1_python3_core/0050_wheel/sources
  layers/layer1_python3_core/0400_prereq_extra_python_packages/Makefile
  layers/layer1_python3_core/0400_prereq_extra_python_packages/Makefile.mk
  layers/layer1_python3_core/0400_prereq_extra_python_packages/requirements-to-freeze.txt
  layers/layer1_python3_core/0400_prereq_extra_python_packages/requirements3.txt
  layers/layer1_python3_core/0500_extra_python_packages/Makefile
  layers/layer1_python3_core/0500_extra_python_packages/Makefile.mk
  layers/layer1_python3_core/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer1_python3_core/0500_extra_python_packages/requirements3.txt
  layers/layer2_python3/0400_prereq_extra_python_packages/requirements-to-freeze.txt
  layers/layer2_python3/0400_prereq_extra_python_packages/requirements3.txt
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
  layers/layer2_python3_circus/0500_circus/requirements3.txt
  layers/layer2_python3_scientific_core/0500_extra_python_packages/requirements3.txt
  layers/layer7_python3_devtools/0500_extra_python_packages/requirements3.txt
Labels: Status: Merge Now, Status: Review Needed

#1083 build: certifi is probably necessary
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Status: Merge Now

#1084 build: certifi is probably necessary
  layers/layer1_python3_core/0500_extra_python_packages/requirements3.txt
  layers/layer2_python3/0400_prereq_extra_python_packages/requirements3.txt
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
  layers/layer2_python3_circus/0500_circus/requirements3.txt
  layers/layer7_python3_devtools/0500_extra_python_packages/requirements3.txt
Labels: Status: Merge Now

#1085 Add certifi
  layers/layer1_python3_core/0500_extra_python_packages/requirements3.txt
  layers/layer2_python3/0400_prereq_extra_python_packages/requirements3.txt
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
  layers/layer2_python3_circus/0500_circus/requirements3.txt
  layers/layer7_python3_devtools/0500_extra_python_packages/requirements3.txt
Labels: Status: Merge Now, Status: Review Needed

#1086 Revert "feat: upgrade setuptools from 42.0.2 to 54.1.2 with refactori…
  .gitignore
  .metwork-framework/components.md
  layers/layer1_python3_core/0030_python3/Makefile.mk
  layers/layer1_python3_core/0032_wheel/sources
  layers/layer1_python3_core/0033_upgrade_pip_setuptools/Makefile.mk
  layers/layer1_python3_core/0033_upgrade_pip_setuptools/requirements-to-freeze.txt
  layers/layer1_python3_core/0033_upgrade_pip_setuptools/requirements3.txt
  layers/layer1_python3_core/0041_six/Makefile
  layers/layer1_python3_core/0041_six/Makefile.mk
  layers/layer1_python3_core/0041_six/sources
  layers/layer1_python3_core/0042_appdirs/Makefile
  layers/layer1_python3_core/0042_appdirs/Makefile.mk
  layers/layer1_python3_core/0042_appdirs/sources
  layers/layer1_python3_core/0043_packaging/Makefile
  layers/layer1_python3_core/0043_packaging/Makefile.mk
  layers/layer1_python3_core/0043_packaging/sources
  layers/layer1_python3_core/0044_setuptools/Makefile
  layers/layer1_python3_core/0044_setuptools/Makefile.mk
  layers/layer1_python3_core/0044_setuptools/sources
  layers/layer1_python3_core/0045_pyparsing/Makefile
  layers/layer1_python3_core/0045_pyparsing/Makefile.mk
  layers/layer1_python3_core/0045_pyparsing/sources
  layers/layer1_python3_core/0046_pip/Makefile
  layers/layer1_python3_core/0046_pip/Makefile.mk
  layers/layer1_python3_core/0046_pip/sources
  layers/layer1_python3_core/0046_virtualenv/Makefile
  layers/layer1_python3_core/0046_virtualenv/Makefile.mk
  layers/layer1_python3_core/0046_virtualenv/sources
  layers/layer1_python3_core/0050_wheel/Makefile
  layers/layer1_python3_core/0050_wheel/Makefile.mk
  layers/layer1_python3_core/0050_wheel/sources
  layers/layer1_python3_core/0400_prereq_extra_python_packages/Makefile.mk
  layers/layer1_python3_core/0400_prereq_extra_python_packages/requirements-to-freeze.txt
  layers/layer1_python3_core/0400_prereq_extra_python_packages/requirements3.txt
  layers/layer1_python3_core/0500_extra_python_packages/Makefile.mk
  layers/layer1_python3_core/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer1_python3_core/0500_extra_python_packages/requirements3.txt
  layers/layer2_python3/0400_prereq_extra_python_packages/requirements-to-freeze.txt
  layers/layer2_python3/0400_prereq_extra_python_packages/requirements3.txt
  layers/layer2_python3_circus/0500_circus/requirements3.txt
  layers/layer2_python3_scientific_core/0500_extra_python_packages/requirements3.txt
  layers/layer7_python3_devtools/0500_extra_python_packages/requirements3.txt
Labels: Status: Merge Now, Status: Review Needed

#1088 feat: upgrade setuptools from 42.0.2 to 54.1.2 with refactoring of la…
  .gitignore
  .metwork-framework/components.md
  layers/layer1_python3_core/0030_python3/Makefile.mk
  layers/layer1_python3_core/0032_wheel/Makefile
  layers/layer1_python3_core/0032_wheel/Makefile.mk
  layers/layer1_python3_core/0032_wheel/sources
  layers/layer1_python3_core/0033_upgrade_pip_setuptools/Makefile
  layers/layer1_python3_core/0033_upgrade_pip_setuptools/Makefile.mk
  layers/layer1_python3_core/0033_upgrade_pip_setuptools/requirements-to-freeze.txt
  layers/layer1_python3_core/0033_upgrade_pip_setuptools/requirements3.txt
  layers/layer1_python3_core/0041_six/Makefile.mk
  layers/layer1_python3_core/0041_six/sources
  layers/layer1_python3_core/0042_appdirs/Makefile.mk
  layers/layer1_python3_core/0042_appdirs/sources
  layers/layer1_python3_core/0043_packaging/Makefile.mk
  layers/layer1_python3_core/0043_packaging/sources
  layers/layer1_python3_core/0044_setuptools/Makefile.mk
  layers/layer1_python3_core/0044_setuptools/sources
  layers/layer1_python3_core/0045_pyparsing/Makefile
  layers/layer1_python3_core/0045_pyparsing/Makefile.mk
  layers/layer1_python3_core/0045_pyparsing/sources
  layers/layer1_python3_core/0046_pip/Makefile
  layers/layer1_python3_core/0046_pip/Makefile.mk
  layers/layer1_python3_core/0046_pip/sources
  layers/layer1_python3_core/0046_virtualenv/Makefile
  layers/layer1_python3_core/0046_virtualenv/Makefile.mk
  layers/layer1_python3_core/0046_virtualenv/sources
  layers/layer1_python3_core/0050_wheel/Makefile
  layers/layer1_python3_core/0050_wheel/sources
  layers/layer1_python3_core/0400_prereq_extra_python_packages/Makefile
  layers/layer1_python3_core/0400_prereq_extra_python_packages/Makefile.mk
  layers/layer1_python3_core/0400_prereq_extra_python_packages/requirements-to-freeze.txt
  layers/layer1_python3_core/0400_prereq_extra_python_packages/requirements3.txt
  layers/layer1_python3_core/0500_extra_python_packages/Makefile
  layers/layer1_python3_core/0500_extra_python_packages/Makefile.mk
  layers/layer1_python3_core/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer1_python3_core/0500_extra_python_packages/requirements3.txt
  layers/layer2_python3/0400_prereq_extra_python_packages/requirements-to-freeze.txt
  layers/layer2_python3/0400_prereq_extra_python_packages/requirements3.txt
  layers/layer2_python3/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
  layers/layer2_python3_circus/0500_circus/requirements3.txt
  layers/layer2_python3_scientific_core/0500_extra_python_packages/requirements3.txt
  layers/layer7_python3_devtools/0500_extra_python_packages/requirements3.txt
Labels: Status: Review Needed

#1091 feat: upgrade from python 3.7.10 to python 3.8.8
  .metwork-framework/components.md
  adm/envtpl
  adm/templates/profile
  bootstrap.sh
  layers/layer1_python3_core/0030_python3/Makefile.mk
  layers/layer1_python3_core/0030_python3/sources
Labels: Status: Review Needed

#1096 build: add python3install_pip in Makefile.standard and use it to buil…
  integration_tests/0004_test_import_python3/import_python3.py
  layers/Makefile.standard
  layers/layer2_python3/0498_configupdater/Makefile.mk
  layers/layer2_python3/0550_bjoern/Makefile.mk
Labels: Status: Review Needed

#1093 feat: upgrade Jinja2 from 2.10.1 to 2.11.3 to fix security vulnerability
  .metwork-framework/components.md
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Status: Review Needed, backport-to-1.0

#1094 feat: upgrade cryptography from 2.9.2 to 3.2.1 to fix security vulner…
  .metwork-framework/components.md
  layers/layer2_python3/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Status: Merge Now, Status: Review Needed

#1099 build: small build changes
  .metwork-framework/components.md
  layers/layer1_python3_core/0032_wheel/Makefile.mk
  layers/layer1_python3_core/0035_certifi/Makefile.mk
  layers/layer2_python3/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
  layers/layer7_python3_devtools/0500_extra_python_packages/requirements3.txt
Labels: Status: Review Needed

#1100 build: remove direct_url.json files (they contain hard path to dev di…
  layers/Makefile.standard
Labels: Status: Review Needed

#1102 feat: security updates (pyyaml 5.4.1 and cryptography 3.3.2)
  .metwork-framework/components.md
  layers/layer2_python3/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Status: Review Needed

#1103 build: new possibilities to install python3 packages using 'pip insta…
  layers/Makefile.standard
Labels: Status: Merge Now, Status: Review Needed

#1104 feat: remove nose-html-reporting which is not python3 compliant
  .metwork-framework/components.md
  layers/layer7_python3_devtools/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer7_python3_devtools/0500_extra_python_packages/requirements3.txt
Labels: Status: Review Needed
