Repository metwork-framework/mfext, pull requests merged in 2021-04, with the labels that each got.

#1107 feat: upgrade Python 3.8 to 3.8.9 (security updates)
  .metwork-framework/components.md
  layers/layer1_python3_core/0030_python3/Makefile.mk
  layers/layer1_python3_core/0030_python3/sources
Labels: Status: Review Needed

#1109 build: do not remove empty file allow_binary_packages
  adm/remove_empty.sh
Labels: Status: Merge Now, Status: Review Needed, backport-to-1.0

#1111 build: update cookiecutter_hooks
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Status: Review Needed

#1113 build: sync common files from github_organization_management repository
  .github/workflows/set_variables.sh
Labels: Status: Merge Now

#1114 build: fix guess_version.sh for release branches
  adm/guess_version.sh
Labels: Status: Review Needed

#1115 build: fix guess_version.sh for release branches (#1114)
  adm/guess_version.sh
Labels: Status: Review Needed

#1116 build: fix permissions
  adm/templates/_mfxxx_wrapper
  adm/templates/cronwrap.sh
  adm/templates/mfxxx_wrapper
Labels: Status: Review Needed
