Repository metwork-framework/mfext, pull requests merged in 2021-06, with the labels that each got.

#1148 feat: add PostGreSQL extension postgresql_airtide
  .metwork-framework/components.md
  layers/layer1_scientific_core/0071_postgresql_airtide/Makefile
  layers/layer1_scientific_core/0071_postgresql_airtide/Makefile.mk
  layers/layer1_scientific_core/0071_postgresql_airtide/sources
Labels: Status: Review Needed

#1150 fix: update acquisition package to fix some issues in mfdata
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Status: Review Needed, backport-to-1.0, backport-to-1.1

#1154 build: postgresql_airtide needs libgfortran.so.5
  layers/layer1_scientific_core/.system_dependencies
Labels: Status: Review Needed

#1153 feat: bump urllib3 from 1.25.11 to 1.26.5 to fix security alert GHSA-…
  .metwork-framework/components.md
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Status: Review Needed

#1156 fix: fix deadlock issue in rich lib by updating
  .metwork-framework/components.md
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Status: Review Needed, backport-to-1.0, backport-to-1.1

#1159 build: replace 'custom' by short commit number or tag name as version…
  .metwork-framework/components.md
  layers/_pip_package_to_yaml.sh
Labels: Status: Review Needed

#1160 build: fix components.md
  .metwork-framework/components.md
Labels: Status: Review Needed

#1161 build: update requirements3.txt
  .metwork-framework/components.md
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: backport-to-1.0, backport-to-1.1

#1165 fix: fix opinionated_configparser in a mfdata corner case
  .metwork-framework/components.md
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Status: Review Needed, backport-to-1.0, backport-to-1.1

#1169 build: fix path to libpng
  layers/layer1_scientific_core/0023_gdal/Makefile.mk
Labels: Status: Merge Now

#1170 fix: update acquisition package to fix an issue in mfdata
  .metwork-framework/components.md
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Status: Review Needed, backport-to-1.0, backport-to-1.1

#1173 fix: fix bad acquisition update
  .metwork-framework/components.md
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Status: Merge Now, Status: Review Needed, backport-to-1.0, backport-to-1.1
