Repository metwork-framework/mfext, pull requests merged in 2022-05, with the labels that each got.

#1343 build: remove system dependencies not required anymore in el8
  layers/layer0_core/.system_dependencies
  layers/layer1_python3_core/.system_dependencies
  layers/layer9_default/.system_dependencies
Labels: Status: Review Needed, Status: Merge Now

#1344 feat: upgrade gdal from 3.0.2 to 3.3.3
  .metwork-framework/components.md
  layers/layer1_scientific_core/0023_gdal/Makefile.mk
  layers/layer1_scientific_core/0023_gdal/patches
  layers/layer1_scientific_core/0023_gdal/rename_g2clib_symbols.patch
  layers/layer1_scientific_core/0023_gdal/sources
Labels: Status: Review Needed

#1345 feat: upgrade python 3.9 to 3.9.12; remove deprecated nose
  .metwork-framework/components.md
  integration_tests/0004_test_import_python3/import_python3.py
  layers/layer1_python3_core/0030_python3/Makefile.mk
  layers/layer1_python3_core/0030_python3/sources
  layers/layer1_python3_core/0033_upgrade_pip_setuptools/requirements-to-freeze.txt
  layers/layer1_python3_core/0033_upgrade_pip_setuptools/requirements3.txt
  layers/layer2_python3/0400_prereq_extra_python_packages/requirements-to-freeze.txt
  layers/layer2_python3/0400_prereq_extra_python_packages/requirements3.txt
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
  layers/layer7_python3_devtools/0500_extra_python_packages/requirements3.txt
Labels: Status: Review Needed

#1346 fix: update envtpl to fix issues with jinja2 new major version (in so…
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Status: Review Needed, Status: Merge Now, backport-to-1.1, backport-to-1.2, backport-to-2.0

#1351 build: fix ci
  .metwork-framework/components.md
  adm/_yaml_to_md.py
Labels: Status: Review Needed, backport-to-1.1, backport-to-1.2, backport-to-2.0

#1355 build: fix ci (#1351)
  adm/_yaml_to_md.py
Labels: Status: Review Needed, Status: Merge Now

#1356 feat: upgrade proj from 6.2.1 to 6.3.2
  .metwork-framework/components.md
  layers/layer1_scientific_core/0015_proj/Makefile.mk
  layers/layer1_scientific_core/0015_proj/sources
Labels: Status: Merge Now

#1358 feat: upgrade proj from 6.2.1 to 6.3.2 and gdal from 3.0.2 to 3.0.4
  .metwork-framework/components.md
  layers/layer1_scientific_core/0015_proj/Makefile.mk
  layers/layer1_scientific_core/0015_proj/sources
  layers/layer1_scientific_core/0023_gdal/Makefile.mk
  layers/layer1_scientific_core/0023_gdal/sources
Labels: Status: Review Needed
