Repository metwork-framework/mfext, pull requests merged in 2022-03, with the labels that each got.

#1291 build: force ci
  README.md
Labels: Status: Merge Now

#1293 build: fix build on dispatch
  .github/workflows/set_variables.sh
Labels: Status: Merge Now

#1294 build: fix build on dispatch
  .github/workflows/set_variables.sh
Labels: Status: Merge Now

#1295 build: fix packaging in some corner cases
  adm/_metwork.spec
Labels: Status: Review Needed, backport-to-1.1, backport-to-1.2

#1301 build: revert : remove useless python3 dep (backport #1298) (#1299)
  layers/layer8_monitoring/.layerapi2_dependencies
Labels: Status: Merge Now

#1304 feat: remove tcltk layer (replaced by usage of system libraries)
  .metwork-framework/components.md
  integration_tests/0004_test_import_python3/.layerapi2_dependencies
  layers/layer0_core/.system_dependencies
  layers/layer0_tcltk/.layerapi2_dependencies
  layers/layer0_tcltk/.layerapi2_label
  layers/layer0_tcltk/.system_dependencies
  layers/layer0_tcltk/0010_tcl/Makefile
  layers/layer0_tcltk/0010_tcl/Makefile.mk
  layers/layer0_tcltk/0010_tcl/sources
  layers/layer0_tcltk/0020_tk/Makefile
  layers/layer0_tcltk/0020_tk/Makefile.mk
  layers/layer0_tcltk/0020_tk/sources
  layers/layer0_tcltk/Makefile
  layers/layer0_tcltk/layer_custom.md
  layers/layer1_python3_core/.layerapi2_dependencies
  layers/layer1_python3_core/0030_python3/Makefile.mk
  layers/layer9_default/.layerapi2_dependencies
Labels: Status: Review Needed

#1305 build: layers refactoring for preparing ldap merge in 1.1 branch
  .metwork-framework/components.md
  adm/templates/circus.ini
  layers/layer8_monitoring/.layerapi2_dependencies
  layers/layer8_python3_monitoring/.layerapi2_dependencies
  layers/layer8_python3_monitoring/.layerapi2_label
  layers/layer8_python3_monitoring/.system_dependencies
  layers/layer8_python3_monitoring/0500_extra_packages/Makefile
  layers/layer8_python3_monitoring/0500_extra_packages/Makefile.mk
  layers/layer8_python3_monitoring/0500_extra_packages/requirements-to-freeze.txt
  layers/layer8_python3_monitoring/0500_extra_packages/requirements3.txt
  layers/layer8_python3_monitoring/Makefile
  layers/layer8_python3_monitoring/layer_custom.md
Labels: Status: Review Needed

#1308 build: force ci
  README.md
Labels: Status: Merge Now

#1309 feat: remove libtiff, openjpeg2, jasper, pixman and cairo builds (replaced by usage of system libraries)
  .metwork-framework/components.md
  layers/layer1_scientific_core/.system_dependencies
  layers/layer1_scientific_core/0004_libtiff/Makefile
  layers/layer1_scientific_core/0004_libtiff/Makefile.mk
  layers/layer1_scientific_core/0004_libtiff/sources
  layers/layer1_scientific_core/0005_openjpeg/Makefile
  layers/layer1_scientific_core/0005_openjpeg/Makefile.mk
  layers/layer1_scientific_core/0005_openjpeg/sources
  layers/layer1_scientific_core/0006_jasper/Makefile
  layers/layer1_scientific_core/0006_jasper/Makefile.mk
  layers/layer1_scientific_core/0006_jasper/build_with_cmake_2x.patch
  layers/layer1_scientific_core/0006_jasper/patches
  layers/layer1_scientific_core/0006_jasper/sources
  layers/layer1_scientific_core/0023_gdal/Makefile.mk
  layers/layer1_scientific_core/0024_pixman/Makefile
  layers/layer1_scientific_core/0024_pixman/Makefile.mk
  layers/layer1_scientific_core/0024_pixman/sources
  layers/layer1_scientific_core/0032_cairo/Makefile
  layers/layer1_scientific_core/0032_cairo/Makefile.mk
  layers/layer1_scientific_core/0032_cairo/sources
Labels: Status: Review Needed

#1310 feat: upgrade postgresql from 13.4 to 14.2
  .metwork-framework/components.md
  layers/layer1_scientific_core/0008_postgresql/Makefile.mk
  layers/layer1_scientific_core/0008_postgresql/sources
Labels: Status: Review Needed

#1312 feat: add ipython in python3_devtools@mfext
  .metwork-framework/components.md
  layers/layer2_python3/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
  layers/layer7_python3_devtools/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer7_python3_devtools/0500_extra_python_packages/requirements3.txt
Labels: Status: Review Needed, Status: Merge Now

#1313 build: obsolete metwork-mfext-layer-tcltk which does not exist anymore
  adm/_metwork.spec
Labels: Status: Merge Now

#1314 build: add libgeotiff.pc
  layers/layer1_scientific_core/0020_libgeotiff/Makefile.mk
  layers/layer1_scientific_core/0020_libgeotiff/libgeotiff.end
Labels: Status: Review Needed

#1315 build: add libgeotiff.pc
  layers/layer1_scientific_core/0020_libgeotiff/Makefile.mk
Labels: Status: Review Needed, Status: Merge Now

#1317 feat: bump paramiko to 2.10.3 to fix a security vulnerability
  .gitignore
  .metwork-framework/components.md
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Status: Review Needed, Status: Merge Now
