Repository metwork-framework/mfext, pull requests merged in 2022-12, with the labels that each got.

#1467 feat: add pywget and sftp_py
  .metwork-framework/components.md
  integration_tests/0004_test_import_python3/import_python3.py
  integration_tests/0005_test_import_python3_bis/import_python3.py
  layers/layer7_python3_devtools/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer7_python3_devtools/0500_extra_python_packages/requirements3.txt
Labels: Status: Review Needed, Status: Merge Now

#1469 build: add psycopg-c (required to run on fedora)
  .metwork-framework/components.md
  integration_tests/0004_test_import_python3/import_python3.py
  integration_tests/0005_test_import_python3_bis/import_python3.py
  layers/layer2_python3_scientific_core/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer2_python3_scientific_core/0500_extra_python_packages/requirements3.txt
Labels: Status: Merge Now, backport-to-2.1

#1471 build: embed libjasper.so.4 (for fedora 37 providing libjasper.so.6)
  layers/layer1_scientific_core/.system_dependencies
  layers/layer1_scientific_core/0001_scientific_system_libraries/libraries.txt
Labels: Status: Merge Now, backport-to-2.1

#1473 fix: fix #956
  .metwork-framework/components.md
  adm/templates/interactive_profile
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Status: Review Needed, backport-to-2.1

#1475 build: fix recent regression
  .metwork-framework/components.md
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Status: Merge Now

#1477 build: upgrade acquisition (keep original filename in trash directory)
  .metwork-framework/components.md
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Status: Merge Now

#1479 build: fix ci in case of triggering
  .github/workflows/build.sh
  .github/workflows/ci.yml
Labels: Status: Merge Now

#1480 build: fix ci
  .github/workflows/ci.yml
Labels: Status: Review Needed, Status: Merge Now

#1482 feat: add release in mfplugin configuration
  .metwork-framework/components.md
  adm/plugin.mk
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Status: Merge Now

#1483 feat: upgrade certifi to 2022.12.7 (security upgrade)
  .metwork-framework/components.md
  layers/layer1_python3_core/0035_certifi/Makefile.mk
  layers/layer1_python3_core/0035_certifi/sources
Labels: Status: Merge Now
