Repository metwork-framework/mfext, pull requests merged in 2023-01, with the labels that each got.

#1486 fix: plugin make - hide commands being executed (#1485)
  adm/plugin.mk
Labels: Status: Review Needed, backport-to-2.1

#1490 fix: .releaseignore / make release : incorrect exclusion with lines beginning with !
  .metwork-framework/components.md
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Status: Review Needed, Status: Merge Now, backport-to-2.1

#1492 fix: update mfplugin to fix a tmpdir plugins issue (mfbase #212)
  .metwork-framework/components.md
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Status: Review Needed, Status: Merge Now, backport-to-2.1

#1495 fix: issue when metwork group exists but is missing in /etc/group
  adm/_metwork.spec
Labels: Status: Merge Now, backport-to-2.1

#1508 build: remove pytest-forked, not required anymore as dependency
  .metwork-framework/components.md
  layers/layer7_python3_devtools/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer7_python3_devtools/0500_extra_python_packages/requirements3.txt
Labels: Status: Merge Now

#1509 build: fix tests
  integration_tests/0004_test_import_python3/import_python3.py
  integration_tests/0005_test_import_python3_bis/import_python3.py
Labels: Status: Merge Now

#1510 feat: upgrade liquidprompt to 2.1.2
  .metwork-framework/components.md
  adm/templates/interactive_profile
  layers/layer0_core/0010_liquidprompt/Makefile.mk
  layers/layer0_core/0010_liquidprompt/sources
Labels: Status: Merge Now

#1511 feat: remove python package future, useless since python2 is dead
  .metwork-framework/components.md
  layers/layer2_python3/0500_extra_python_packages/requirements3.txt
Labels: Status: Merge Now

#1512 build: fix tests
  integration_tests/0004_test_import_python3/import_python3.py
  integration_tests/0005_test_import_python3_bis/import_python3.py
Labels: Status: Merge Now

#1515 feat: add python-ldap and dependencies in layer python3_devtools
  .metwork-framework/components.md
  integration_tests/0004_test_import_python3/import_python3.py
  integration_tests/0005_test_import_python3_bis/import_python3.py
  layers/layer7_python3_devtools/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer7_python3_devtools/0500_extra_python_packages/requirements3.txt
Labels: Status: Review Needed, Status: Merge Now, backport-to-2.1

#1527 build: post installation for main package
  adm/_metwork.spec
Labels: Status: Review Needed

#1525 feat: keep permissions on /home/mfxxx and .ssh directory when upgrading
  adm/_metwork.spec
Labels: Status: Review Needed, backport-to-2.1

#1530 fix: do not echo on /dev/stderr, which doesn't work after sudo
  adm/pip_wrapper
Labels: Status: Review Needed, backport-to-2.1
