Repository metwork-framework/mfext, pull requests merged in 2023-04, with the labels that each got.

#1570 fix: prevent error messages when uninstalling rpms in some corny case
  adm/_metwork.spec
Labels: Status: Review Needed, Status: Merge Now, backport-to-2.1

#1573 feat: save module status to json file (#1572)
  adm/_module_status_json.py
  adm/templates/mfxxx.autorestart
Labels: Status: Review Needed

#1574 build: fix adm Makefile
  adm/Makefile
Labels: Status: Merge Now
