Repository metwork-framework/mfext, pull requests merged in 2024-03, with the labels that each got.

#1815 feat: add security patch for nginx
  layers/layer.mk
  layers/layer1_openresty/0100_openresty/ngx_http_mp4_module.patch
  layers/layer1_openresty/0100_openresty/patches
Labels: Status: Merge Now

#1816 fix: update circus (to fix preexec_fn issue)
  .metwork-framework/components.md
  layers/layer2_python3_circus/0500_circus/requirements-to-freeze.txt
  layers/layer2_python3_circus/0500_circus/requirements3.txt
Labels: Status: Merge Now, backport-to-2.0, backport-to-2.1, backport-to-2.2

#1820 feat: add python package astral
  .metwork-framework/components.md
  layers/layer2_python3_scientific_core/0500_extra_python_packages/allow_binary_packages
  layers/layer2_python3_scientific_core/0500_extra_python_packages/requirements-to-freeze.txt
  layers/layer2_python3_scientific_core/0500_extra_python_packages/requirements3.txt
Labels: Status: Merge Now, backport-to-2.2

#1825 fix: fix mfbase.start in case NOINIT
  adm/templates/mfxxx.start
Labels: Status: Review Needed, backport-to-2.0, backport-to-2.1, backport-to-2.2

#1831 fix: Revert "fix: update circus (to fix preexec_fn issue)"
  .metwork-framework/components.md
  layers/layer2_python3_circus/0500_circus/requirements3.txt
Labels: Status: Merge Now

#1830 fix: useless module mffront in service usage (closes #1829)
  adm/metwork
Labels: Status: Review Needed
